# Konfiguračný súbor pre slovenskú normalizáciu miest a obcí
# Tento súbor obsahuje slovník pre automatickú konverziu názvov bez diakritiky
# Vygenerované z: https://github.com/m-a-k-o/slovenske-obce

SLOVENSKE_MESTA = {
    "abelova": "Ábelová",
    "abovce": "Abovce",
    "abraham": "Abrahám",
    "abrahamovce": "Abrahámovce",
    "abramova": "Abramová",
    "abranovce": "Abranovce",
    "adamovske kochanovce": "Adamovské Kochanovce",
    "adidovce": "Adidovce",
    "aleksince": "Alekšince",
    "andovce": "Andovce",
    "andrejova": "Andrejová",
    "ardanovce": "Ardanovce",
    "ardovo": "Ardovo",
    "arnutovce": "Arnutovce",
    "bab": "Báb",
    "babie": "Babie",
    "babin": "Babín",
    "babina": "Babiná",
    "babindol": "Babindol",
    "babinec": "Babinec",
    "bac": "Báč",
    "backa": "Bačka",
    "backov": "Bačkov",
    "backovik": "Bačkovík",
    "bacuch": "Bacúch",
    "bacurov": "Bacúrov",
    "badan": "Baďan",
    "badice": "Bádice",
    "badin": "Badín",
    "bahon": "Báhoň",
    "bajany": "Bajany",
    "bajc": "Bajč",
    "bajerov": "Bajerov",
    "bajerovce": "Bajerovce",
    "bajka": "Bajka",
    "bajtava": "Bajtava",
    "baka": "Baka",
    "balaze": "Baláže",
    "baldovce": "Baldovce",
    "balog nad iplom": "Balog nad Ipľom",
    "balon": "Baloň",
    "bana": "Baňa",
    "banka": "Banka",
    "banov": "Bánov",
    "banovce nad bebravou": "Bánovce nad Bebravou",
    "banovce nad ondavou": "Bánovce nad Ondavou",
    "banska bela": "Banská Belá",
    "banska bystrica": "Banská Bystrica",
    "banska stiavnica": "Banská Štiavnica",
    "banske": "Banské",
    "bansky studenec": "Banský Studenec",
    "bara": "Bara",
    "barca": "Barca",
    "bardejov": "Bardejov",
    "bardonovo": "Bardoňovo",
    "bartosova lehotka": "Bartošova Lehôtka",
    "bartosovce": "Bartošovce",
    "baska": "Baška",
    "baskovce": "Baškovce",
    "basovce": "Bašovce",
    "batizovce": "Batizovce",
    "batka": "Bátka",
    "batorova": "Bátorová",
    "batorove kosihy": "Bátorove Kosihy",
    "batovce": "Bátovce",
    "becherov": "Becherov",
    "beckov": "Beckov",
    "beharovce": "Beharovce",
    "bela": "Belá",
    "bela nad cirochou": "Belá nad Cirochou",
    "bela-dulice": "Belá-Dulice",
    "beladice": "Beladice",
    "belejovce": "Belejovce",
    "belin": "Belín",
    "belina": "Belina",
    "belince": "Belince",
    "bellova ves": "Bellova Ves",
    "beloveza": "Beloveža",
    "beluj": "Beluj",
    "belusa": "Beluša",
    "belza": "Belža",
    "benadikova": "Beňadiková",
    "benadikovce": "Beňadikovce",
    "benadovo": "Beňadovo",
    "benatina": "Beňatina",
    "beniakovce": "Beniakovce",
    "benice": "Benice",
    "benkovce": "Benkovce",
    "benus": "Beňuš",
    "bernolakovo": "Bernolákovo",
    "bertotovce": "Bertotovce",
    "besa": "Beša",
    "besenov": "Bešeňov",
    "besenova": "Bešeňová",
    "betlanovce": "Betlanovce",
    "betliar": "Betliar",
    "bezovce": "Bežovce",
    "bidovce": "Bidovce",
    "biel": "Biel",
    "bielovce": "Bielovce",
    "biely kostol": "Biely Kostol",
    "bijacovce": "Bijacovce",
    "bilkove humence": "Bílkove Humence",
    "bina": "Bíňa",
    "binovce": "Bíňovce",
    "biskupice": "Biskupice",
    "biskupova": "Biskupová",
    "bitarova": "Bitarová",
    "blahova": "Blahová",
    "blatna na ostrove": "Blatná na Ostrove",
    "blatna polianka": "Blatná Polianka",
    "blatne": "Blatné",
    "blatne remety": "Blatné Remety",
    "blatne revistia": "Blatné Revištia",
    "blatnica": "Blatnica",
    "blazice": "Blažice",
    "blazovce": "Blažovce",
    "blesovce": "Blesovce",
    "blhovce": "Blhovce",
    "bobot": "Bobot",
    "bobrov": "Bobrov",
    "bobrovcek": "Bobrovček",
    "bobrovec": "Bobrovec",
    "bobrovnik": "Bobrovník",
    "bociar": "Bočiar",
    "bodiky": "Bodíky",
    "bodina": "Bodiná",
    "bodorova": "Bodorová",
    "bodovce": "Bodovce",
    "bodruzal": "Bodružal",
    "bodza": "Bodza",
    "bodzianske luky": "Bodzianske Lúky",
    "bogliarka": "Bogliarka",
    "bohdanovce": "Bohdanovce",
    "bohdanovce nad trnavou": "Bohdanovce nad Trnavou",
    "bohelov": "Boheľov",
    "bohunice": "Bohunice",
    "bohunovo": "Bohúňovo",
    "bojna": "Bojná",
    "bojnice": "Bojnice",
    "bojnicky": "Bojničky",
    "bol": "Boľ",
    "boldog": "Boldog",
    "boleraz": "Boleráz",
    "bolesov": "Bolešov",
    "boliarov": "Boliarov",
    "bolkovce": "Boľkovce",
    "borcany": "Borčany",
    "borcice": "Borčice",
    "borcova": "Borcová",
    "borinka": "Borinka",
    "borka": "Bôrka",
    "borova": "Borová",
    "borovce": "Borovce",
    "borsa": "Borša",
    "borsky mikulas": "Borský Mikuláš",
    "borsky svaty jur": "Borský Svätý Jur",
    "bory": "Bory",
    "bosaca": "Bošáca",
    "bosany": "Bošany",
    "botany": "Boťany",
    "bottovo": "Bottovo",
    "bracovce": "Bracovce",
    "branc": "Branč",
    "branovo": "Branovo",
    "bratislava i": "Bratislava I",
    "bratislava ii": "Bratislava II",
    "bratislava iii": "Bratislava III",
    "bratislava iv": "Bratislava IV",
    "bratislava v": "Bratislava V",
    "bravacovo": "Braväcovo",
    "brdarka": "Brdárka",
    "brehov": "Brehov",
    "brehy": "Brehy",
    "brekov": "Brekov",
    "brestov": "Brestov",
    "brestov nad laborcom": "Brestov nad Laborcom",
    "brestovany": "Brestovany",
    "brestovec": "Brestovec",
    "bretejovce": "Bretejovce",
    "bretka": "Bretka",
    "breza": "Breza",
    "brezany": "Brežany",
    "brezina": "Brezina",
    "breziny": "Breziny",
    "breznica": "Breznica",
    "breznicka": "Breznička",
    "brezno": "Brezno",
    "brezolupy": "Brezolupy",
    "brezov": "Brezov",
    "brezova pod bradlom": "Brezová pod Bradlom",
    "brezovec": "Brezovec",
    "brezovica": "Brezovica",
    "brezovicka": "Brezovička",
    "brezovka": "Brezovka",
    "brhlovce": "Brhlovce",
    "briestie": "Brieštie",
    "brodske": "Brodské",
    "brodzany": "Brodzany",
    "brunovce": "Brunovce",
    "brusnica": "Brusnica",
    "brusnik": "Brusník",
    "brusno": "Brusno",
    "brutovce": "Brutovce",
    "bruty": "Bruty",
    "brvniste": "Brvnište",
    "brzotin": "Brzotín",
    "buc": "Búč",
    "bucany": "Bučany",
    "buclovany": "Buclovany",
    "budca": "Budča",
    "budikovany": "Budikovany",
    "budimir": "Budimír",
    "budina": "Budiná",
    "budince": "Budince",
    "budis": "Budiš",
    "budkovce": "Budkovce",
    "budmerice": "Budmerice",
    "buglovce": "Buglovce",
    "bukova": "Buková",
    "bukovce": "Bukovce",
    "bukovec": "Bukovec",
    "bukovina": "Bukovina",
    "bulhary": "Bulhary",
    "bunetice": "Bunetice",
    "bunkovce": "Bunkovce",
    "busince": "Bušince",
    "busovce": "Bušovce",
    "buzica": "Buzica",
    "buzitka": "Buzitka",
    "bysta": "Byšta",
    "bystra": "Bystrá",
    "bystrany": "Bystrany",
    "bystre": "Bystré",
    "bystricany": "Bystričany",
    "bystricka": "Bystrička",
    "bytca": "Bytča",
    "bzany": "Bžany",
    "bzenica": "Bzenica",
    "bzenov": "Bzenov",
    "bzince pod javorinou": "Bzince pod Javorinou",
    "bziny": "Bziny",
    "bzovik": "Bzovík",
    "bzovska lehotka": "Bzovská Lehôtka",
    "cab": "Čab",
    "cabaj-capor": "Cabaj-Čápor",
    "cabalovce": "Čabalovce",
    "cabiny": "Čabiny",
    "cabov": "Cabov",
    "cabradsky vrbovok": "Čabradský Vrbovok",
    "cachtice": "Čachtice",
    "cadca": "Čadca",
    "cajkov": "Čajkov",
    "caka": "Čaka",
    "cakajovce": "Čakajovce",
    "cakanovce": "Čakanovce",
    "cakany": "Čakany",
    "caklov": "Čaklov",
    "cakov": "Cakov",
    "calovec": "Čalovec",
    "camovce": "Čamovce",
    "cana": "Čaňa",
    "caradice": "Čaradice",
    "cary": "Čáry",
    "casta": "Častá",
    "castkov": "Častkov",
    "castkovce": "Častkovce",
    "cata": "Čata",
    "cataj": "Čataj",
    "cavoj": "Čavoj",
    "cebovce": "Čebovce",
    "cecehov": "Čečehov",
    "cecejovce": "Čečejovce",
    "cechy": "Čechy",
    "cechynce": "Čechynce",
    "cejkov": "Cejkov",
    "cekovce": "Čekovce",
    "celadice": "Čeľadice",
    "celadince": "Čeľadince",
    "celare": "Čeláre",
    "celkova lehota": "Čelkova Lehota",
    "celovce": "Čeľovce",
    "cenkovce": "Čenkovce",
    "cerenany": "Čereňany",
    "cerencany": "Čerenčany",
    "cerhov": "Čerhov",
    "cerin": "Čerín",
    "cermany": "Čermany",
    "cernik": "Černík",
    "cernina": "Černina",
    "cernochov": "Černochov",
    "cerova": "Cerová",
    "cerovo": "Cerovo",
    "certizne": "Čertižné",
    "cervena voda": "Červená Voda",
    "cervenany": "Červeňany",
    "cervenica": "Červenica",
    "cervenica pri sabinove": "Červenica pri Sabinove",
    "cervenik": "Červeník",
    "cerveny hradok": "Červený Hrádok",
    "cerveny kamen": "Červený Kameň",
    "cerveny klastor": "Červený Kláštor",
    "ceske brezovo": "České Brezovo",
    "cestice": "Cestice",
    "chanava": "Chanava",
    "chlaba": "Chľaba",
    "chlebnice": "Chlebnice",
    "chlmec": "Chlmec",
    "chmelnica": "Chmeľnica",
    "chmelov": "Chmeľov",
    "chmelova": "Chmeľová",
    "chmelovec": "Chmeľovec",
    "chminany": "Chmiňany",
    "chminianska nova ves": "Chminianska Nová Ves",
    "chminianske jakubovany": "Chminianske Jakubovany",
    "choca": "Choča",
    "chocholna-velcice": "Chocholná-Velčice",
    "chonkovce": "Choňkovce",
    "chorvatsky grob": "Chorvátsky Grob",
    "chorvaty": "Chorváty",
    "chotca": "Chotča",
    "chotin": "Chotín",
    "chrabrany": "Chrabrany",
    "chramec": "Chrámec",
    "chrast nad hornadom": "Chrasť nad Hornádom",
    "chrastince": "Chrastince",
    "chrastne": "Chrastné",
    "chrenovec-brusno": "Chrenovec-Brusno",
    "chropov": "Chropov",
    "chrtany": "Chrťany",
    "chtelnica": "Chtelnica",
    "chuda lehota": "Chudá Lehota",
    "chvalova": "Chvalová",
    "chvojnica": "Chvojnica",
    "chynorany": "Chynorany",
    "chyzne": "Chyžné",
    "cicarovce": "Čičarovce",
    "cicava": "Čičava",
    "cicmany": "Čičmany",
    "cicov": "Číčov",
    "cierna": "Čierna",
    "cierna lehota": "Čierna Lehota",
    "cierna nad tisou": "Čierna nad Tisou",
    "cierna voda": "Čierna Voda",
    "cierne": "Čierne",
    "cierne klacany": "Čierne Kľačany",
    "cierne nad toplou": "Čierne nad Topľou",
    "cierne pole": "Čierne Pole",
    "cierny balog": "Čierny Balog",
    "cierny brod": "Čierny Brod",
    "cierny potok": "Čierny Potok",
    "cifare": "Čifáre",
    "cifer": "Cífer",
    "cigel": "Cigeľ",
    "cigelka": "Cigeľka",
    "cigla": "Cigla",
    "cilizska radvan": "Čiližská Radvaň",
    "cimenna": "Cimenná",
    "cimhova": "Čimhová",
    "cinobana": "Cinobaňa",
    "circ": "Čirč",
    "ciz": "Číž",
    "cizatice": "Čižatice",
    "coltovo": "Čoltovo",
    "cremosne": "Čremošné",
    "cucma": "Čučma",
    "cukalovce": "Čukalovce",
    "dacov": "Ďačov",
    "dacov lom": "Dačov Lom",
    "daletice": "Daletice",
    "danisovce": "Danišovce",
    "danova": "Ďanová",
    "dapalovce": "Ďapalovce",
    "dargov": "Dargov",
    "davidov": "Davidov",
    "debrad": "Debraď",
    "dechtice": "Dechtice",
    "dedacov": "Dedačov",
    "dedina mladeze": "Dedina Mládeže",
    "dedinka": "Dedinka",
    "dedinky": "Dedinky",
    "dekys": "Dekýš",
    "demandice": "Demandice",
    "demanovska dolina": "Demänovská Dolina",
    "demjata": "Demjata",
    "detrik": "Detrík",
    "detva": "Detva",
    "detvianska huta": "Detvianska Huta",
    "devicany": "Devičany",
    "devicie": "Devičie",
    "dezerice": "Dežerice",
    "diakova": "Diaková",
    "diakovce": "Diakovce",
    "diviacka nova ves": "Diviacka Nová Ves",
    "diviaky nad nitricou": "Diviaky nad Nitricou",
    "divin": "Divín",
    "divina": "Divina",
    "divinka": "Divinka",
    "dlha": "Dlhá",
    "dlha nad kysucou": "Dlhá nad Kysucou",
    "dlha nad oravou": "Dlhá nad Oravou",
    "dlha nad vahom": "Dlhá nad Váhom",
    "dlha ves": "Dlhá Ves",
    "dlhe klcovo": "Dlhé Klčovo",
    "dlhe nad cirochou": "Dlhé nad Cirochou",
    "dlhe pole": "Dlhé Pole",
    "dlhe straze": "Dlhé Stráže",
    "dlhona": "Dlhoňa",
    "dlzin": "Dlžín",
    "dobra": "Dobrá",
    "dobra niva": "Dobrá Niva",
    "dobra voda": "Dobrá Voda",
    "dobroc": "Dobroč",
    "dobrohost": "Dobrohošť",
    "dobroslava": "Dobroslava",
    "dobsina": "Dobšiná",
    "dohnany": "Dohňany",
    "dojc": "Dojč",
    "dolany": "Doľany",
    "dolinka": "Dolinka",
    "dolna breznica": "Dolná Breznica",
    "dolna krupa": "Dolná Krupá",
    "dolna lehota": "Dolná Lehota",
    "dolna marikova": "Dolná Mariková",
    "dolna micina": "Dolná Mičiná",
    "dolna poruba": "Dolná Poruba",
    "dolna sec": "Dolná Seč",
    "dolna streda": "Dolná Streda",
    "dolna strehova": "Dolná Strehová",
    "dolna suca": "Dolná Súča",
    "dolna tizina": "Dolná Tižina",
    "dolna trnavka": "Dolná Trnávka",
    "dolna ves": "Dolná Ves",
    "dolna zdana": "Dolná Ždaňa",
    "dolne dubove": "Dolné Dubové",
    "dolne kockovce": "Dolné Kočkovce",
    "dolne lefantovce": "Dolné Lefantovce",
    "dolne lovcice": "Dolné Lovčice",
    "dolne mladonice": "Dolné Mladonice",
    "dolne nastice": "Dolné Naštice",
    "dolne obdokovce": "Dolné Obdokovce",
    "dolne oresany": "Dolné Orešany",
    "dolne otrokovce": "Dolné Otrokovce",
    "dolne plachtince": "Dolné Plachtince",
    "dolne saliby": "Dolné Saliby",
    "dolne semerovce": "Dolné Semerovce",
    "dolne srnie": "Dolné Srnie",
    "dolne strhare": "Dolné Strháre",
    "dolne trhoviste": "Dolné Trhovište",
    "dolne vestenice": "Dolné Vestenice",
    "dolne zahorany": "Dolné Zahorany",
    "dolne zelenice": "Dolné Zelenice",
    "dolny badin": "Dolný Badín",
    "dolny bar": "Dolný Bar",
    "dolny chotar": "Dolný Chotár",
    "dolny harmanec": "Dolný Harmanec",
    "dolny hricov": "Dolný Hričov",
    "dolny kalnik": "Dolný Kalník",
    "dolny kubin": "Dolný Kubín",
    "dolny lieskov": "Dolný Lieskov",
    "dolny lopasov": "Dolný Lopašov",
    "dolny ohaj": "Dolný Ohaj",
    "dolny pial": "Dolný Pial",
    "dolny stal": "Dolný Štál",
    "dolny vadicov": "Dolný Vadičov",
    "domadice": "Domadice",
    "domaniky": "Domaníky",
    "domaniza": "Domaniža",
    "domanovce": "Domaňovce",
    "donovaly": "Donovaly",
    "drabsko": "Drábsko",
    "drahnov": "Drahňov",
    "drahovce": "Drahovce",
    "dravce": "Dravce",
    "drazice": "Dražice",
    "drazkovce": "Dražkovce",
    "drazovce": "Drážovce",
    "driencany": "Drienčany",
    "drienica": "Drienica",
    "drienov": "Drienov",
    "drienovec": "Drienovec",
    "drienovo": "Drienovo",
    "drienovska nova ves": "Drienovská Nová Ves",
    "drietoma": "Drietoma",
    "drna": "Drňa",
    "drnava": "Drnava",
    "druzstevna pri hornade": "Družstevná pri Hornáde",
    "drzenice": "Drženice",
    "drzkovce": "Držkovce",
    "dubakovo": "Ďubákovo",
    "dubinne": "Dubinné",
    "dubnica nad vahom": "Dubnica nad Váhom",
    "dubnicka": "Dubnička",
    "dubnik": "Dubník",
    "dubno": "Dubno",
    "dubodiel": "Dubodiel",
    "dubova": "Dubová",
    "dubovany": "Dubovany",
    "dubovce": "Dubovce",
    "dubove": "Dubové",
    "dubovec": "Dubovec",
    "dubovica": "Dubovica",
    "dubrava": "Dúbrava",
    "dubravica": "Dúbravica",
    "dubravka": "Dúbravka",
    "dubravy": "Dúbravy",
    "ducove": "Ducové",
    "dudince": "Dudince",
    "dukovce": "Dukovce",
    "dulov": "Dulov",
    "dulova ves": "Dulova Ves",
    "dulovce": "Dulovce",
    "dulovo": "Dulovo",
    "dunajov": "Dunajov",
    "dunajska luzna": "Dunajská Lužná",
    "dunajska streda": "Dunajská Streda",
    "dunajsky klatov": "Dunajský Klátov",
    "duplin": "Duplín",
    "durcina": "Ďurčiná",
    "durdos": "Ďurďoš",
    "durdosik": "Ďurďošík",
    "durdove": "Ďurďové",
    "durkov": "Ďurkov",
    "durkova": "Ďurková",
    "durkovce": "Ďurkovce",
    "dvorany nad nitrou": "Dvorany nad Nitrou",
    "dvorec": "Dvorec",
    "dvorianky": "Dvorianky",
    "dvorniky": "Dvorníky",
    "dvorniky-vcelare": "Dvorníky-Včeláre",
    "dvory nad zitavou": "Dvory nad Žitavou",
    "egres": "Egreš",
    "fackov": "Fačkov",
    "falkusovce": "Falkušovce",
    "farna": "Farná",
    "fekisovce": "Fekišovce",
    "figa": "Figa",
    "fijas": "Fijaš",
    "filakovo": "Fiľakovo",
    "filakovske kovace": "Fiľakovské Kováče",
    "fintice": "Fintice",
    "folkusova": "Folkušová",
    "forbasy": "Forbasy",
    "fricka": "Frička",
    "frickovce": "Fričkovce",
    "fricovce": "Fričovce",
    "fulianka": "Fulianka",
    "gabcikovo": "Gabčíkovo",
    "gaboltov": "Gaboltov",
    "gajary": "Gajary",
    "galanta": "Galanta",
    "galovany": "Galovany",
    "gan": "Gáň",
    "ganovce": "Gánovce",
    "gbelany": "Gbeľany",
    "gbelce": "Gbelce",
    "gbely": "Gbely",
    "geca": "Geča",
    "gelnica": "Gelnica",
    "gemer": "Gemer",
    "gemercek": "Gemerček",
    "gemerska horka": "Gemerská Hôrka",
    "gemerska panica": "Gemerská Panica",
    "gemerska poloma": "Gemerská Poloma",
    "gemerska ves": "Gemerská Ves",
    "gemerske dechtare": "Gemerské Dechtáre",
    "gemerske michalovce": "Gemerské Michalovce",
    "gemerske teplice": "Gemerské Teplice",
    "gemersky jablonec": "Gemerský Jablonec",
    "gemersky sad": "Gemerský Sad",
    "geraltov": "Geraltov",
    "gerlachov": "Gerlachov",
    "giglovce": "Giglovce",
    "giraltovce": "Giraltovce",
    "girovce": "Girovce",
    "glabusovce": "Glabušovce",
    "gocaltovo": "Gočaltovo",
    "gocovo": "Gočovo",
    "golianovo": "Golianovo",
    "gortva": "Gortva",
    "gotovany": "Gôtovany",
    "granc-petrovce": "Granč-Petrovce",
    "gregorova vieska": "Gregorova Vieska",
    "gregorovce": "Gregorovce",
    "gribov": "Gribov",
    "gruzovce": "Gruzovce",
    "gynov": "Gyňov",
    "habovka": "Habovka",
    "habura": "Habura",
    "hacava": "Hačava",
    "haj": "Háj",
    "hajna nova ves": "Hajná Nová Ves",
    "hajnacka": "Hajnáčka",
    "hajske": "Hájske",
    "hajtovka": "Hajtovka",
    "halacovce": "Haláčovce",
    "halic": "Halič",
    "haligovce": "Haligovce",
    "haluzice": "Haluzice",
    "hamuliakovo": "Hamuliakovo",
    "handlova": "Handlová",
    "hanigovce": "Hanigovce",
    "haniska": "Haniska",
    "hankova": "Hanková",
    "hankovce": "Hankovce",
    "hanusovce nad toplou": "Hanušovce nad Topľou",
    "harakovce": "Harakovce",
    "harhaj": "Harhaj",
    "harichovce": "Harichovce",
    "harmanec": "Harmanec",
    "hatalov": "Hatalov",
    "hatne": "Hatné",
    "havaj": "Havaj",
    "havka": "Havka",
    "havranec": "Havranec",
    "hazin": "Hažín",
    "hazin nad cirochou": "Hažín nad Cirochou",
    "hazlin": "Hažlín",
    "helcmanovce": "Helcmanovce",
    "helpa": "Heľpa",
    "henckovce": "Henckovce",
    "henclova": "Henclová",
    "hencovce": "Hencovce",
    "hendrichovce": "Hendrichovce",
    "herlany": "Herľany",
    "hermanovce": "Hermanovce",
    "hermanovce nad toplou": "Hermanovce nad Topľou",
    "hertnik": "Hertník",
    "hervartov": "Hervartov",
    "hiadel": "Hiadeľ",
    "hincovce": "Hincovce",
    "hladovka": "Hladovka",
    "hlboke": "Hlboké",
    "hlboke nad vahom": "Hlboké nad Váhom",
    "hlinik nad hronom": "Hliník nad Hronom",
    "hlinne": "Hlinné",
    "hlivistia": "Hlivištia",
    "hlohovec": "Hlohovec",
    "hniezdne": "Hniezdne",
    "hnilcik": "Hnilčík",
    "hnilec": "Hnilec",
    "hnojne": "Hnojné",
    "hnusta": "Hnúšťa",
    "hodejov": "Hodejov",
    "hodejovec": "Hodejovec",
    "hodkovce": "Hodkovce",
    "hodrusa-hamre": "Hodruša-Hámre",
    "hokovce": "Hokovce",
    "holcikovce": "Holčíkovce",
    "holiare": "Holiare",
    "holic": "Holíč",
    "holice": "Holice",
    "holisa": "Holiša",
    "holumnica": "Holumnica",
    "honce": "Honce",
    "hontianska vrbica": "Hontianska Vrbica",
    "hontianske moravce": "Hontianske Moravce",
    "hontianske nemce": "Hontianske Nemce",
    "hontianske tesare": "Hontianske Tesáre",
    "hontianske trstany": "Hontianske Trsťany",
    "horka": "Hôrka",
    "horka nad vahom": "Hôrka nad Váhom",
    "horky": "Hôrky",
    "horna": "Horňa",
    "horna breznica": "Horná Breznica",
    "horna kralova": "Horná Kráľová",
    "horna krupa": "Horná Krupá",
    "horna lehota": "Horná Lehota",
    "horna marikova": "Horná Mariková",
    "horna micina": "Horná Mičiná",
    "horna poruba": "Horná Poruba",
    "horna poton": "Horná Potôň",
    "horna sec": "Horná Seč",
    "horna streda": "Horná Streda",
    "horna strehova": "Horná Strehová",
    "horna stubna": "Horná Štubňa",
    "horna suca": "Horná Súča",
    "horna ves": "Horná Ves",
    "horna zdana": "Horná Ždaňa",
    "hornany": "Horňany",
    "horne chlebany": "Horné Chlebany",
    "horne dubove": "Horné Dubové",
    "horne hamre": "Horné Hámre",
    "horne lefantovce": "Horné Lefantovce",
    "horne mladonice": "Horné Mladonice",
    "horne myto": "Horné Mýto",
    "horne nastice": "Horné Naštice",
    "horne obdokovce": "Horné Obdokovce",
    "horne oresany": "Horné Orešany",
    "horne otrokovce": "Horné Otrokovce",
    "horne plachtince": "Horné Plachtince",
    "horne prsany": "Horné Pršany",
    "horne saliby": "Horné Saliby",
    "horne semerovce": "Horné Semerovce",
    "horne srnie": "Horné Srnie",
    "horne stitare": "Horné Štitáre",
    "horne strhare": "Horné Strháre",
    "horne trhoviste": "Horné Trhovište",
    "horne turovce": "Horné Turovce",
    "horne vestenice": "Horné Vestenice",
    "horne zahorany": "Horné Zahorany",
    "horne zelenice": "Horné Zelenice",
    "horny badin": "Horný Badín",
    "horny bar": "Horný Bar",
    "horny hricov": "Horný Hričov",
    "horny kalnik": "Horný Kalník",
    "horny lieskov": "Horný Lieskov",
    "horny pial": "Horný Pial",
    "horny tisovnik": "Horný Tisovník",
    "horny vadicov": "Horný Vadičov",
    "horovce": "Horovce",
    "hoste": "Hoste",
    "hostice": "Hostice",
    "hostie": "Hostie",
    "hostisovce": "Hostišovce",
    "hostova": "Hosťová",
    "hostovce": "Hosťovce",
    "hostovice": "Hostovice",
    "hozelec": "Hozelec",
    "hrabicov": "Hrabičov",
    "hrabkov": "Hrabkov",
    "hrabova roztoka": "Hrabová Roztoka",
    "hrabovcik": "Hrabovčík",
    "hrabovec": "Hrabovec",
    "hrabovec nad laborcom": "Hrabovec nad Laborcom",
    "hrabovka": "Hrabovka",
    "hrabske": "Hrabské",
    "hrabusice": "Hrabušice",
    "hrachoviste": "Hrachovište",
    "hrachovo": "Hrachovo",
    "hradisko": "Hradisko",
    "hradiste": "Hradište",
    "hradiste pod vratnom": "Hradište pod Vrátnom",
    "hradok": "Hrádok",
    "hran": "Hraň",
    "hranicne": "Hraničné",
    "hranovnica": "Hranovnica",
    "hrasne": "Hrašné",
    "hrasovik": "Hrašovík",
    "hrcel": "Hrčeľ",
    "hrhov": "Hrhov",
    "hriadky": "Hriadky",
    "hricovske podhradie": "Hričovské Podhradie",
    "hrinova": "Hriňová",
    "hrisovce": "Hrišovce",
    "hrkovce": "Hrkovce",
    "hrlica": "Hrlica",
    "hrnciarovce nad parnou": "Hrnčiarovce nad Parnou",
    "hrnciarska ves": "Hrnčiarska Ves",
    "hrnciarske zaluzany": "Hrnčiarske Zalužany",
    "hrochot": "Hrochoť",
    "hromos": "Hromoš",
    "hronec": "Hronec",
    "hronovce": "Hronovce",
    "hronsek": "Hronsek",
    "hronska breznica": "Hronská Breznica",
    "hronska dubrava": "Hronská Dúbrava",
    "hronske klacany": "Hronské Kľačany",
    "hronske kosihy": "Hronské Kosihy",
    "hronsky benadik": "Hronský Beňadik",
    "hruba borsa": "Hrubá Borša",
    "hrubonovo": "Hruboňovo",
    "hrubov": "Hrubov",
    "hruby sur": "Hrubý Šúr",
    "hrusov": "Hrušov",
    "hrusovany": "Hrušovany",
    "hrusovo": "Hrušovo",
    "hrustin": "Hruštín",
    "hubice": "Hubice",
    "hubina": "Hubina",
    "hubosovce": "Hubošovce",
    "hubova": "Hubová",
    "hubovo": "Hubovo",
    "hucin": "Hucín",
    "hudcovce": "Hudcovce",
    "hul": "Hul",
    "humenne": "Humenné",
    "huncovce": "Huncovce",
    "hunkovce": "Hunkovce",
    "hurbanova ves": "Hurbanova Ves",
    "hurbanovo": "Hurbanovo",
    "husak": "Husák",
    "husina": "Husiná",
    "hutka": "Hutka",
    "huty": "Huty",
    "hviezdoslavov": "Hviezdoslavov",
    "hvozdnica": "Hvozdnica",
    "hybe": "Hybe",
    "hylov": "Hýľov",
    "igram": "Igram",
    "ihlany": "Ihľany",
    "ihrac": "Ihráč",
    "ilava": "Ilava",
    "iliasovce": "Iliašovce",
    "ilija": "Ilija",
    "imel": "Imeľ",
    "ina": "Iňa",
    "inacovce": "Iňačovce",
    "inovce": "Inovce",
    "ipelske predmostie": "Ipeľské Predmostie",
    "ipelske ulany": "Ipeľské Úľany",
    "ipelsky sokolec": "Ipeľský Sokolec",
    "istebne": "Istebné",
    "ivachnova": "Ivachnová",
    "ivancina": "Ivančiná",
    "ivanice": "Ivanice",
    "ivanka pri dunaji": "Ivanka pri Dunaji",
    "ivanka pri nitre": "Ivanka pri Nitre",
    "ivanovce": "Ivanovce",
    "iza": "Iža",
    "izipovce": "Ižipovce",
    "izkovce": "Ižkovce",
    "jablon": "Jabloň",
    "jablonec": "Jablonec",
    "jablonica": "Jablonica",
    "jablonka": "Jablonka",
    "jablonov": "Jablonov",
    "jablonov nad turnou": "Jablonov nad Turňou",
    "jablonovce": "Jabloňovce",
    "jablonove": "Jablonové",
    "jacovce": "Jacovce",
    "jahodna": "Jahodná",
    "jaklovce": "Jaklovce",
    "jakovany": "Jakovany",
    "jakubany": "Jakubany",
    "jakubov": "Jakubov",
    "jakubova vola": "Jakubova Voľa",
    "jakubovany": "Jakubovany",
    "jakusovce": "Jakušovce",
    "jalova": "Jalová",
    "jalovec": "Jalovec",
    "jalsove": "Jalšové",
    "jalsovik": "Jalšovík",
    "jamnik": "Jamník",
    "janice": "Janice",
    "janik": "Janík",
    "janiky": "Janíky",
    "jankovce": "Jankovce",
    "janov": "Janov",
    "janova lehota": "Janova Lehota",
    "janovce": "Jánovce",
    "janovik": "Janovík",
    "jaraba": "Jarabá",
    "jarabina": "Jarabina",
    "jarok": "Jarok",
    "jarovnice": "Jarovnice",
    "jasenica": "Jasenica",
    "jasenie": "Jasenie",
    "jasenov": "Jasenov",
    "jasenova": "Jasenová",
    "jasenovce": "Jasenovce",
    "jasenove": "Jasenové",
    "jasenovo": "Jasenovo",
    "jaslovske bohunice": "Jaslovské Bohunice",
    "jasov": "Jasov",
    "jasova": "Jasová",
    "jastraba": "Jastrabá",
    "jastrabie nad toplou": "Jastrabie nad Topľou",
    "jastrabie pri michalovciach": "Jastrabie pri Michalovciach",
    "jatov": "Jatov",
    "jazernica": "Jazernica",
    "jedlinka": "Jedlinka",
    "jedlove kostolany": "Jedľové Kostoľany",
    "jelenec": "Jelenec",
    "jelka": "Jelka",
    "jelsava": "Jelšava",
    "jelsovce": "Jelšovce",
    "jelsovec": "Jelšovec",
    "jenkovce": "Jenkovce",
    "jesenske": "Jesenské",
    "jeskova ves": "Ješkova Ves",
    "jestice": "Jestice",
    "jezersko": "Jezersko",
    "jovice": "Jovice",
    "jovsa": "Jovsa",
    "jur nad hronom": "Jur nad Hronom",
    "jurkova vola": "Jurkova Voľa",
    "jurova": "Jurová",
    "jurske": "Jurské",
    "juskova vola": "Juskova Voľa",
    "kacanov": "Kačanov",
    "kajal": "Kajal",
    "kalamenova": "Kaľamenová",
    "kalameny": "Kalameny",
    "kalava": "Kaľava",
    "kalinkovo": "Kalinkovo",
    "kalinov": "Kalinov",
    "kalinovo": "Kalinovo",
    "kalna nad hronom": "Kalná nad Hronom",
    "kalna roztoka": "Kalná Roztoka",
    "kalnica": "Kálnica",
    "kalniste": "Kalnište",
    "kalonda": "Kalonda",
    "kalosa": "Kaloša",
    "kalsa": "Kalša",
    "kaluza": "Kaluža",
    "kamanova": "Kamanová",
    "kamenany": "Kameňany",
    "kamenec pod vtacnikom": "Kamenec pod Vtáčnikom",
    "kamenica": "Kamenica",
    "kamenica nad cirochou": "Kamenica nad Cirochou",
    "kamenica nad hronom": "Kamenica nad Hronom",
    "kamenicany": "Kameničany",
    "kamenicna": "Kameničná",
    "kamenin": "Kamenín",
    "kamenna poruba": "Kamenná Poruba",
    "kamenne kosihy": "Kamenné Kosihy",
    "kamenny most": "Kamenný Most",
    "kamienka": "Kamienka",
    "kanianka": "Kanianka",
    "kapince": "Kapince",
    "kapisova": "Kapišová",
    "kaplna": "Kaplna",
    "kapusany": "Kapušany",
    "kapusianske klacany": "Kapušianske Kľačany",
    "karlova": "Karlová",
    "karna": "Karná",
    "kasov": "Kašov",
    "katlovce": "Kátlovce",
    "katov": "Kátov",
    "kazimir": "Kazimír",
    "kecerovce": "Kecerovce",
    "kecerovsky lipovec": "Kecerovský Lipovec",
    "kechnec": "Kechnec",
    "keckovce": "Kečkovce",
    "kecovo": "Kečovo",
    "kendice": "Kendice",
    "kesovce": "Kesovce",
    "ket": "Keť",
    "kezmarok": "Kežmarok",
    "kiarov": "Kiarov",
    "klacany": "Kľačany",
    "klace": "Kľače",
    "klacno": "Kľačno",
    "kladzany": "Kladzany",
    "klak": "Kľak",
    "klasov": "Klasov",
    "klastor pod znievom": "Kláštor pod Znievom",
    "klatova nova ves": "Klátova Nová Ves",
    "klcov": "Klčov",
    "klenany": "Kleňany",
    "klenov": "Klenov",
    "klenova": "Klenová",
    "klenovec": "Klenovec",
    "kliestina": "Klieština",
    "klin": "Klin",
    "klin nad bodrogom": "Klin nad Bodrogom",
    "klizska nema": "Klížska Nemá",
    "klokoc": "Klokoč",
    "klokocov": "Klokočov",
    "klubina": "Klubina",
    "klucovec": "Kľúčovec",
    "kluknava": "Kluknava",
    "klusov": "Kľušov",
    "kmetovo": "Kmeťovo",
    "kobeliarovo": "Kobeliarovo",
    "kobylnice": "Kobylnice",
    "kobyly": "Kobyly",
    "kocelovce": "Koceľovce",
    "kochanovce": "Kochanovce",
    "kociha": "Kociha",
    "kocin-lancar": "Kočín-Lančár",
    "kocovce": "Kočovce",
    "kocurany": "Kocurany",
    "kojatice": "Kojatice",
    "kojsov": "Kojšov",
    "kokava nad rimavicou": "Kokava nad Rimavicou",
    "kokosovce": "Kokošovce",
    "koksov-baksa": "Kokšov-Bakša",
    "kolackov": "Kolačkov",
    "kolacno": "Kolačno",
    "kolare": "Koláre",
    "kolarovice": "Kolárovice",
    "kolarovo": "Kolárovo",
    "kolbasov": "Kolbasov",
    "kolbovce": "Kolbovce",
    "kolibabovce": "Kolibabovce",
    "kolinany": "Kolíňany",
    "kolinovce": "Kolinovce",
    "kolonica": "Kolonica",
    "kolta": "Kolta",
    "komarany": "Komárany",
    "komarno": "Komárno",
    "komarov": "Komárov",
    "komarovce": "Komárovce",
    "komjatice": "Komjatice",
    "komjatna": "Komjatná",
    "komoca": "Komoča",
    "koniarovce": "Koniarovce",
    "konradovce": "Konrádovce",
    "konska": "Konská",
    "konus": "Koňuš",
    "kopcany": "Kopčany",
    "kopernica": "Kopernica",
    "koplotovce": "Koplotovce",
    "koprivnica": "Koprivnica",
    "kordiky": "Kordíky",
    "korejovce": "Korejovce",
    "korna": "Korňa",
    "koromla": "Koromľa",
    "korunkova": "Korunková",
    "korytarky": "Korytárky",
    "korytne": "Korytné",
    "kos": "Koš",
    "kosariska": "Košariská",
    "kosarovce": "Košarovce",
    "koseca": "Košeca",
    "kosecke podhradie": "Košecké Podhradie",
    "kosice i": "Košice I",
    "kosice ii": "Košice II",
    "kosice iii": "Košice III",
    "kosice iv": "Košice IV",
    "kosicka bela": "Košická Belá",
    "kosicka polianka": "Košická Polianka",
    "kosicke olsany": "Košické Oľšany",
    "kosicky klecenov": "Košický Klečenov",
    "kosihovce": "Kosihovce",
    "kosihy nad iplom": "Kosihy nad Ipľom",
    "koskovce": "Koškovce",
    "kosolna": "Košolná",
    "kosorin": "Kosorín",
    "kostany nad turcom": "Košťany nad Turcom",
    "kostolany nad hornadom": "Kostoľany nad Hornádom",
    "kostolany pod tribecom": "Kostoľany pod Tribečom",
    "kostolec": "Kostolec",
    "kostoliste": "Kostolište",
    "kostolna pri dunaji": "Kostolná pri Dunaji",
    "kostolna ves": "Kostolná Ves",
    "kostolna-zariecie": "Kostolná-Záriečie",
    "kostolne": "Kostolné",
    "kostolne kracany": "Kostolné Kračany",
    "kosuty": "Košúty",
    "kotesova": "Kotešová",
    "kotmanova": "Kotmanová",
    "kotrcina lucka": "Kotrčiná Lúčka",
    "kovacova": "Kováčová",
    "kovacovce": "Kováčovce",
    "kovalov": "Koválov",
    "kovalovec": "Koválovec",
    "kovarce": "Kovarce",
    "kozany": "Kožany",
    "kozarovce": "Kozárovce",
    "kozelnik": "Kozelník",
    "kozi vrbovok": "Kozí Vrbovok",
    "kozuchov": "Kožuchov",
    "kozuchovce": "Kožuchovce",
    "kracunovce": "Kračúnovce",
    "krahule": "Krahule",
    "krajna bystra": "Krajná Bystrá",
    "krajna polana": "Krajná Poľana",
    "krajna porubka": "Krajná Porúbka",
    "krajne": "Krajné",
    "krajne cierno": "Krajné Čierno",
    "krakovany": "Krakovany",
    "kral": "Kráľ",
    "kraliky": "Králiky",
    "kralov brod": "Kráľov Brod",
    "kralova lehota": "Kráľova Lehota",
    "kralova nad vahom": "Kráľová nad Váhom",
    "kralova pri senci": "Kráľová pri Senci",
    "kralovany": "Kraľovany",
    "kralovce": "Kráľovce",
    "kralovce-krnisov": "Kráľovce-Krnišov",
    "kralovicove kracany": "Kráľovičove Kračany",
    "kralovsky chlmec": "Kráľovský Chlmec",
    "kraskovo": "Kraskovo",
    "krasna luka": "Krásna Lúka",
    "krasna ves": "Krásna Ves",
    "krasnany": "Krasňany",
    "krasno": "Krásno",
    "krasno nad kysucou": "Krásno nad Kysucou",
    "krasnohorska dlha luka": "Krásnohorská Dlhá Lúka",
    "krasnohorske podhradie": "Krásnohorské Podhradie",
    "krasnovce": "Krásnovce",
    "krasny brod": "Krásny Brod",
    "kravany": "Kravany",
    "kravany nad dunajom": "Kravany nad Dunajom",
    "krcava": "Krčava",
    "kremna": "Kremná",
    "kremnica": "Kremnica",
    "kremnicke bane": "Kremnické Bane",
    "krislovce": "Krišľovce",
    "krisovska lieskova": "Krišovská Liesková",
    "kristy": "Kristy",
    "kriva": "Krivá",
    "krivan": "Kriváň",
    "krivany": "Krivany",
    "krive": "Krivé",
    "krivoklat": "Krivoklát",
    "krivosud-bodovka": "Krivosúd-Bodovka",
    "krize": "Kríže",
    "krizova ves": "Krížová Ves",
    "krizovany": "Krížovany",
    "krizovany nad dudvahom": "Križovany nad Dudváhom",
    "krna": "Krná",
    "krnca": "Krnča",
    "krokava": "Krokava",
    "krompachy": "Krompachy",
    "krpelany": "Krpeľany",
    "krskany": "Krškany",
    "krtovce": "Krtovce",
    "krucov": "Kručov",
    "krupina": "Krupina",
    "krusetnica": "Krušetnica",
    "krusinec": "Krušinec",
    "krusovce": "Krušovce",
    "kruzlov": "Kružlov",
    "kruzlova": "Kružlová",
    "kruzna": "Kružná",
    "kruzno": "Kružno",
    "ksinna": "Kšinná",
    "kubanovo": "Kubáňovo",
    "kuchyna": "Kuchyňa",
    "kucin": "Kučín",
    "kuklov": "Kuklov",
    "kukova": "Kuková",
    "kukucinov": "Kukučínov",
    "kunerad": "Kunerad",
    "kunesov": "Kunešov",
    "kunova teplica": "Kunova Teplica",
    "kuralany": "Kuraľany",
    "kurima": "Kurima",
    "kurimany": "Kurimany",
    "kurimka": "Kurimka",
    "kurov": "Kurov",
    "kusin": "Kusín",
    "kutniky": "Kútniky",
    "kuty": "Kúty",
    "kuzmice": "Kuzmice",
    "kvacany": "Kvačany",
    "kvakovce": "Kvakovce",
    "kvasov": "Kvašov",
    "kvetoslavov": "Kvetoslavov",
    "kyjatice": "Kyjatice",
    "kyjov": "Kyjov",
    "kyncelova": "Kynceľová",
    "kysak": "Kysak",
    "kyselica": "Kyselica",
    "kysta": "Kysta",
    "kysucke nove mesto": "Kysucké Nové Mesto",
    "kysucky lieskovec": "Kysucký Lieskovec",
    "lab": "Láb",
    "lackov": "Lackov",
    "lackova": "Lacková",
    "lackovce": "Lackovce",
    "lada": "Lada",
    "ladce": "Ladce",
    "ladice": "Ladice",
    "ladmovce": "Ladmovce",
    "ladomerska vieska": "Ladomerská Vieska",
    "ladomirov": "Ladomirov",
    "ladomirova": "Ladomirová",
    "ladzany": "Ladzany",
    "laksarska nova ves": "Lakšárska Nová Ves",
    "lascov": "Lascov",
    "laskar": "Laskár",
    "laskovce": "Laškovce",
    "lastomir": "Lastomír",
    "lastovce": "Lastovce",
    "latky": "Látky",
    "lazany": "Lažany",
    "lazisko": "Lazisko",
    "lazy pod makytou": "Lazy pod Makytou",
    "lechnica": "Lechnica",
    "lednica": "Lednica",
    "lednicke rovne": "Lednické Rovne",
    "legnava": "Legnava",
    "lehnice": "Lehnice",
    "lehota": "Lehota",
    "lehota nad rimavicou": "Lehota nad Rimavicou",
    "lehota pod vtacnikom": "Lehota pod Vtáčnikom",
    "lehotka": "Lehôtka",
    "lehotka pod brehmi": "Lehôtka pod Brehmi",
    "lekarovce": "Lekárovce",
    "lela": "Leľa",
    "leles": "Leles",
    "lemesany": "Lemešany",
    "lenartov": "Lenartov",
    "lenartovce": "Lenartovce",
    "lendak": "Lendak",
    "lenka": "Lenka",
    "lentvora": "Lentvora",
    "leopoldov": "Leopoldov",
    "lesenice": "Lesenice",
    "lesicek": "Lesíček",
    "lesne": "Lesné",
    "lesnica": "Lesnica",
    "lest (vojensky obvod)": "Lešť (vojenský obvod)",
    "lestiny": "Leštiny",
    "letanovce": "Letanovce",
    "letnicie": "Letničie",
    "levare": "Leváre",
    "levice": "Levice",
    "levkuska": "Levkuška",
    "levoca": "Levoča",
    "leziachov": "Ležiachov",
    "libichava": "Libichava",
    "licartovce": "Ličartovce",
    "licince": "Licince",
    "liesek": "Liesek",
    "lieskovany": "Lieskovany",
    "lieskovec": "Lieskovec",
    "liesno": "Liešno",
    "liestany": "Liešťany",
    "lietava": "Lietava",
    "lietavska lucka": "Lietavská Lúčka",
    "lietavska svinna-babkov": "Lietavská Svinná-Babkov",
    "likavka": "Likavka",
    "limbach": "Limbach",
    "lipany": "Lipany",
    "lipnik": "Lipník",
    "lipniky": "Lipníky",
    "lipova": "Lipová",
    "lipovany": "Lipovany",
    "lipovce": "Lipovce",
    "lipove": "Lipové",
    "lipovec": "Lipovec",
    "lipovnik": "Lipovník",
    "liptovska anna": "Liptovská Anna",
    "liptovska kokava": "Liptovská Kokava",
    "liptovska luzna": "Liptovská Lúžna",
    "liptovska osada": "Liptovská Osada",
    "liptovska porubka": "Liptovská Porúbka",
    "liptovska sielnica": "Liptovská Sielnica",
    "liptovska stiavnica": "Liptovská Štiavnica",
    "liptovska tepla": "Liptovská Teplá",
    "liptovska teplicka": "Liptovská Teplička",
    "liptovske beharovce": "Liptovské Beharovce",
    "liptovske klacany": "Liptovské Kľačany",
    "liptovske matiasovce": "Liptovské Matiašovce",
    "liptovske revuce": "Liptovské Revúce",
    "liptovske sliace": "Liptovské Sliače",
    "liptovsky hradok": "Liptovský Hrádok",
    "liptovsky jan": "Liptovský Ján",
    "liptovsky michal": "Liptovský Michal",
    "liptovsky mikulas": "Liptovský Mikuláš",
    "liptovsky ondrej": "Liptovský Ondrej",
    "liptovsky peter": "Liptovský Peter",
    "liptovsky trnovec": "Liptovský Trnovec",
    "liskova": "Lisková",
    "lisov": "Lišov",
    "litava": "Litava",
    "litmanova": "Litmanová",
    "livina": "Livina",
    "livinske opatovce": "Livinské Opatovce",
    "livov": "Livov",
    "livovska huta": "Livovská Huta",
    "lodno": "Lodno",
    "lok": "Lok",
    "lokca": "Lokca",
    "lom nad rimavicou": "Lom nad Rimavicou",
    "lomna": "Lomná",
    "lomne": "Lomné",
    "lomnicka": "Lomnička",
    "lontov": "Lontov",
    "lopasov": "Lopašov",
    "lopuchov": "Lopúchov",
    "lopusne pazite": "Lopušné Pažite",
    "losonec": "Lošonec",
    "lovca": "Lovča",
    "lovce": "Lovce",
    "lovcica-trubin": "Lovčica-Trubín",
    "lovinobana": "Lovinobaňa",
    "lozin": "Ložín",
    "lozorno": "Lozorno",
    "luba": "Ľubá",
    "lubela": "Ľubeľa",
    "lubenik": "Lubeník",
    "lubica": "Ľubica",
    "lubietova": "Ľubietová",
    "lubina": "Lubina",
    "lubisa": "Ľubiša",
    "lubochna": "Ľubochňa",
    "luborec": "Ľuboreč",
    "luboriecka": "Ľuboriečka",
    "lubotice": "Ľubotice",
    "lubotin": "Ľubotín",
    "lubovec": "Ľubovec",
    "luc na ostrove": "Lúč na Ostrove",
    "lucatin": "Lučatín",
    "lucenec": "Lučenec",
    "lucina": "Lúčina",
    "lucivna": "Lučivná",
    "lucka": "Lúčka",
    "lucky": "Lúčky",
    "lucnica nad zitavou": "Lúčnica nad Žitavou",
    "ludanice": "Ludanice",
    "ludovitova": "Ľudovítová",
    "ludrova": "Ludrová",
    "luhyna": "Luhyňa",
    "luka": "Lúka",
    "lukacovce": "Lukáčovce",
    "lukavica": "Lukavica",
    "lukov": "Lukov",
    "lukovistia": "Lukovištia",
    "luky": "Lúky",
    "lula": "Lula",
    "lupoc": "Lupoč",
    "lutila": "Lutila",
    "lutina": "Ľutina",
    "lutise": "Lutiše",
    "lutov": "Ľutov",
    "luzany": "Lužany",
    "luzany pri topli": "Lužany pri Topli",
    "luzianky": "Lužianky",
    "lysa pod makytou": "Lysá pod Makytou",
    "lysica": "Lysica",
    "machulince": "Machulince",
    "macov": "Macov",
    "mad": "Mad",
    "madunice": "Madunice",
    "magnezitovce": "Magnezitovce",
    "majcichov": "Majcichov",
    "majere": "Majere",
    "majerovce": "Majerovce",
    "makov": "Makov",
    "makovce": "Makovce",
    "mala calomija": "Malá Čalomija",
    "mala causa": "Malá Čausa",
    "mala cierna": "Malá Čierna",
    "mala domasa": "Malá Domaša",
    "mala frankova": "Malá Franková",
    "mala hradna": "Malá Hradná",
    "mala ida": "Malá Ida",
    "mala lehota": "Malá Lehota",
    "mala lodina": "Malá Lodina",
    "mala maca": "Malá Mača",
    "mala nad hronom": "Malá nad Hronom",
    "mala polana": "Malá Poľana",
    "mala trna": "Malá Tŕňa",
    "malachov": "Malachov",
    "malacky": "Malacky",
    "malas": "Málaš",
    "malatina": "Malatiná",
    "malatiny": "Malatíny",
    "malcice": "Malčice",
    "malcov": "Malcov",
    "male borove": "Malé Borové",
    "male chyndice": "Malé Chyndice",
    "male dvorniky": "Malé Dvorníky",
    "male hoste": "Malé Hoste",
    "male kosihy": "Malé Kosihy",
    "male kozmalovce": "Malé Kozmálovce",
    "male krstenany": "Malé Kršteňany",
    "male lednice": "Malé Lednice",
    "male levare": "Malé Leváre",
    "male ludince": "Malé Ludince",
    "male ozorovce": "Malé Ozorovce",
    "male raskovce": "Malé Raškovce",
    "male ripnany": "Malé Ripňany",
    "male straciny": "Malé Straciny",
    "male trakany": "Malé Trakany",
    "male uherce": "Malé Uherce",
    "male vozokany": "Malé Vozokany",
    "male zaluzie": "Malé Zálužie",
    "male zlievce": "Malé Zlievce",
    "malinec": "Málinec",
    "malinova": "Malinová",
    "malinovo": "Malinovo",
    "maluzina": "Malužiná",
    "maly cepcin": "Malý Čepčín",
    "maly cetin": "Malý Cetín",
    "maly hores": "Malý Horeš",
    "maly kamenec": "Malý Kamenec",
    "maly krtis": "Malý Krtíš",
    "maly lapas": "Malý Lapáš",
    "maly lipnik": "Malý Lipník",
    "maly saris": "Malý Šariš",
    "maly slavkov": "Malý Slavkov",
    "maly slivnik": "Malý Slivník",
    "malzenice": "Malženice",
    "mana": "Maňa",
    "mankovce": "Mankovce",
    "marcelova": "Marcelová",
    "margecany": "Margecany",
    "marhan": "Marhaň",
    "marianka": "Marianka",
    "markovce": "Markovce",
    "markuska": "Markuška",
    "markusovce": "Markušovce",
    "marsova-rasov": "Maršová-Rašov",
    "martin": "Martin",
    "martin nad zitavou": "Martin nad Žitavou",
    "martincek": "Martinček",
    "martinova": "Martinová",
    "martovce": "Martovce",
    "maskova": "Mašková",
    "maskovce": "Maškovce",
    "matejovce nad hornadom": "Matejovce nad Hornádom",
    "matiaska": "Matiaška",
    "matiasovce": "Matiašovce",
    "matovce": "Matovce",
    "matovske vojkovce": "Maťovské Vojkovce",
    "matuskovo": "Matúškovo",
    "matysova": "Matysová",
    "medovarce": "Medovarce",
    "medvedie": "Medvedie",
    "medvedov": "Medveďov",
    "medzany": "Medzany",
    "medzev": "Medzev",
    "medzianky": "Medzianky",
    "medzibrod": "Medzibrod",
    "medzibrodie nad oravou": "Medzibrodie nad Oravou",
    "medzilaborce": "Medzilaborce",
    "melcice-lieskove": "Melčice-Lieskové",
    "melek": "Melek",
    "meliata": "Meliata",
    "mengusovce": "Mengusovce",
    "merasice": "Merašice",
    "mernik": "Merník",
    "mestecko": "Mestečko",
    "mestisko": "Mestisko",
    "micakovce": "Mičakovce",
    "michajlov": "Michajlov",
    "michal na ostrove": "Michal na Ostrove",
    "michal nad zitavou": "Michal nad Žitavou",
    "michalany": "Michaľany",
    "michalkova": "Michalková",
    "michalok": "Michalok",
    "michalova": "Michalová",
    "michalovce": "Michalovce",
    "mierovo": "Mierovo",
    "miezgovce": "Miezgovce",
    "miklusovce": "Miklušovce",
    "mikova": "Miková",
    "mikulasova": "Mikulášová",
    "mikusovce": "Mikušovce",
    "milhost": "Milhosť",
    "miloslavov": "Miloslavov",
    "milpos": "Milpoš",
    "minovce": "Miňovce",
    "mirkovce": "Mirkovce",
    "mirola": "Miroľa",
    "mladzovo": "Mládzovo",
    "mlynarovce": "Mlynárovce",
    "mlynceky": "Mlynčeky",
    "mlynica": "Mlynica",
    "mlynky": "Mlynky",
    "mnichova lehota": "Mníchova Lehota",
    "mnisek nad hnilcom": "Mníšek nad Hnilcom",
    "mnisek nad popradom": "Mníšek nad Popradom",
    "moca": "Moča",
    "mocenok": "Močenok",
    "mociar": "Močiar",
    "modra": "Modra",
    "modra nad cirochou": "Modra nad Cirochou",
    "modrany": "Modrany",
    "modrova": "Modrová",
    "modrovka": "Modrovka",
    "modry kamen": "Modrý Kameň",
    "mojmirovce": "Mojmírovce",
    "mojs": "Mojš",
    "mojtin": "Mojtín",
    "mojzesovo": "Mojzesovo",
    "mokra luka": "Mokrá Lúka",
    "mokrance": "Mokrance",
    "mokroluh": "Mokroluh",
    "mokry haj": "Mokrý Háj",
    "molca": "Môlča",
    "moldava nad bodvou": "Moldava nad Bodvou",
    "moravany": "Moravany",
    "moravany nad vahom": "Moravany nad Váhom",
    "moravske lieskove": "Moravské Lieskové",
    "moravsky svaty jan": "Moravský Svätý Ján",
    "moskovec": "Moškovec",
    "mosovce": "Mošovce",
    "most pri bratislave": "Most pri Bratislave",
    "mostenica": "Moštenica",
    "mostova": "Mostová",
    "mosurov": "Mošurov",
    "motesice": "Motešice",
    "motycky": "Motyčky",
    "mrazovce": "Mrázovce",
    "mucin": "Mučín",
    "mudronovo": "Mudroňovo",
    "mudrovce": "Mudrovce",
    "mula": "Muľa",
    "muran": "Muráň",
    "muranska dlha luka": "Muránska Dlhá Lúka",
    "muranska huta": "Muránska Huta",
    "muranska lehota": "Muránska Lehota",
    "muranska zdychava": "Muránska Zdychava",
    "mutne": "Mútne",
    "muzla": "Mužla",
    "myjava": "Myjava",
    "myslina": "Myslina",
    "mytna": "Mýtna",
    "mytne ludany": "Mýtne Ludany",
    "myto pod dumbierom": "Mýto pod Ďumbierom",
    "nacina ves": "Nacina Ves",
    "nadlice": "Nadlice",
    "nagov": "Ňagov",
    "nahac": "Naháč",
    "nalepkovo": "Nálepkovo",
    "namestovo": "Námestovo",
    "nana": "Nána",
    "nandraz": "Nandraž",
    "narad": "Ňárad",
    "nechvalova polianka": "Nechválova Polianka",
    "necpaly": "Necpaly",
    "nedanovce": "Nedanovce",
    "nedasovce": "Nedašovce",
    "neded": "Neded",
    "nededza": "Nededza",
    "nedozery-brezany": "Nedožery-Brezany",
    "nemce": "Nemce",
    "nemcice": "Nemčice",
    "nemcinany": "Nemčiňany",
    "nemcovce": "Nemcovce",
    "nemecka": "Nemecká",
    "nemecky": "Nemečky",
    "nemesany": "Nemešany",
    "nemsova": "Nemšová",
    "nenince": "Nenince",
    "neporadza": "Neporadza",
    "neslusa": "Nesluša",
    "nesvady": "Nesvady",
    "neverice": "Neverice",
    "nevidzany": "Nevidzany",
    "nevolne": "Nevoľné",
    "nezbudska lucka": "Nezbudská Lúčka",
    "nimnica": "Nimnica",
    "nitra": "Nitra",
    "nitra nad iplom": "Nitra nad Ipľom",
    "nitrianska blatnica": "Nitrianska Blatnica",
    "nitrianska streda": "Nitrianska Streda",
    "nitrianske hrnciarovce": "Nitrianske Hrnčiarovce",
    "nitrianske pravno": "Nitrianske Pravno",
    "nitrianske rudno": "Nitrianske Rudno",
    "nitrianske sucany": "Nitrianske Sučany",
    "nitrica": "Nitrica",
    "nizna": "Nižná",
    "nizna boca": "Nižná Boca",
    "nizna hutka": "Nižná Hutka",
    "nizna jablonka": "Nižná Jablonka",
    "nizna jedlova": "Nižná Jedľová",
    "nizna kamenica": "Nižná Kamenica",
    "nizna mysla": "Nižná Myšľa",
    "nizna olsava": "Nižná Olšava",
    "nizna pisana": "Nižná Pisaná",
    "nizna polianka": "Nižná Polianka",
    "nizna rybnica": "Nižná Rybnica",
    "nizna sitnica": "Nižná Sitnica",
    "nizna slana": "Nižná Slaná",
    "nizna vola": "Nižná Voľa",
    "nizne ladickovce": "Nižné Ladičkovce",
    "nizne nemecke": "Nižné Nemecké",
    "nizne repase": "Nižné Repaše",
    "nizne ruzbachy": "Nižné Ružbachy",
    "nizny caj": "Nižný Čaj",
    "nizny hrabovec": "Nižný Hrabovec",
    "nizny hrusov": "Nižný Hrušov",
    "nizny klatov": "Nižný Klátov",
    "nizny komarnik": "Nižný Komárnik",
    "nizny krucov": "Nižný Kručov",
    "nizny lanec": "Nižný Lánec",
    "nizny mirosov": "Nižný Mirošov",
    "nizny orlik": "Nižný Orlík",
    "nizny skalnik": "Nižný Skálnik",
    "nizny slavkov": "Nižný Slavkov",
    "nizny tvarozec": "Nižný Tvarožec",
    "nizny zipov": "Nižný Žipov",
    "nolcovo": "Nolčovo",
    "norovce": "Norovce",
    "nova bana": "Nová Baňa",
    "nova basta": "Nová Bašta",
    "nova bosaca": "Nová Bošáca",
    "nova bystrica": "Nová Bystrica",
    "nova dedina": "Nová Dedina",
    "nova dedinka": "Nová Dedinka",
    "nova dubnica": "Nová Dubnica",
    "nova kelca": "Nová Kelča",
    "nova lehota": "Nová Lehota",
    "nova lesna": "Nová Lesná",
    "nova lubovna": "Nová Ľubovňa",
    "nova polhora": "Nová Polhora",
    "nova polianka": "Nová Polianka",
    "nova sedlica": "Nová Sedlica",
    "nova ves": "Nová Ves",
    "nova ves nad vahom": "Nová Ves nad Váhom",
    "nova ves nad zitavou": "Nová Ves nad Žitavou",
    "nova vieska": "Nová Vieska",
    "novacany": "Nováčany",
    "novaky": "Nováky",
    "nove hony": "Nové Hony",
    "nove mesto nad vahom": "Nové Mesto nad Váhom",
    "nove sady": "Nové Sady",
    "nove zamky": "Nové Zámky",
    "novosad": "Novosad",
    "novot": "Novoť",
    "novy ruskov": "Nový Ruskov",
    "novy salas": "Nový Salaš",
    "novy svet": "Nový Svet",
    "novy tekov": "Nový Tekov",
    "novy zivot": "Nový Život",
    "nyrovce": "Nýrovce",
    "obeckov": "Obeckov",
    "obid": "Obid",
    "obisovce": "Obišovce",
    "oborin": "Oborín",
    "obrucne": "Obručné",
    "obyce": "Obyce",
    "ochodnica": "Ochodnica",
    "ochtina": "Ochtiná",
    "ockov": "Očkov",
    "ocova": "Očová",
    "odorin": "Odorín",
    "ohrady": "Ohrady",
    "ohradzany": "Ohradzany",
    "okoc": "Okoč",
    "okolicna na ostrove": "Okoličná na Ostrove",
    "okruhle": "Okrúhle",
    "okruzna": "Okružná",
    "olcnava": "Olcnava",
    "oldza": "Oľdza",
    "olejnikov": "Olejníkov",
    "olesna": "Olešná",
    "olka": "Oľka",
    "olovary": "Olováry",
    "olsavce": "Oľšavce",
    "olsavica": "Oľšavica",
    "olsavka": "Oľšavka",
    "olsinkov": "Oľšinkov",
    "olsov": "Oľšov",
    "olsovany": "Olšovany",
    "omastina": "Omastiná",
    "omsenie": "Omšenie",
    "ondavka": "Ondavka",
    "ondavske matiasovce": "Ondavské Matiašovce",
    "ondrasova": "Ondrašová",
    "ondrasovce": "Ondrašovce",
    "ondrejovce": "Ondrejovce",
    "opatka": "Opátka",
    "opatovce": "Opatovce",
    "opatovce nad nitrou": "Opatovce nad Nitrou",
    "opatovska nova ves": "Opatovská Nová Ves",
    "opava": "Opava",
    "opina": "Opiná",
    "opoj": "Opoj",
    "oponice": "Oponice",
    "oravce": "Oravce",
    "oravka": "Orávka",
    "oravska jasenica": "Oravská Jasenica",
    "oravska lesna": "Oravská Lesná",
    "oravska polhora": "Oravská Polhora",
    "oravska poruba": "Oravská Poruba",
    "oravske vesele": "Oravské Veselé",
    "oravsky biely potok": "Oravský Biely Potok",
    "oravsky podzamok": "Oravský Podzámok",
    "ordzovany": "Ordzovany",
    "orechova": "Orechová",
    "orechova poton": "Orechová Potôň",
    "oresany": "Orešany",
    "oreske": "Oreské",
    "orlov": "Orlov",
    "orovnica": "Orovnica",
    "ortutova": "Ortuťová",
    "osadka": "Osádka",
    "osadne": "Osadné",
    "oscadnica": "Oščadnica",
    "osikov": "Osikov",
    "oslany": "Oslany",
    "osrblie": "Osrblie",
    "ostra luka": "Ostrá Lúka",
    "ostratice": "Ostratice",
    "ostrov": "Ostrov",
    "ostrovany": "Ostrovany",
    "ostry grun": "Ostrý Grúň",
    "osturna": "Osturňa",
    "osuske": "Osuské",
    "otrhanky": "Otrhánky",
    "otrocok": "Otročok",
    "ovciarsko": "Ovčiarsko",
    "ovcie": "Ovčie",
    "ozdany": "Ožďany",
    "ozdin": "Ozdín",
    "paca": "Pača",
    "padan": "Padáň",
    "padarovce": "Padarovce",
    "pakostov": "Pakostov",
    "palarikovo": "Palárikovo",
    "palin": "Palín",
    "palota": "Palota",
    "pana": "Paňa",
    "panicke dravce": "Panické Dravce",
    "panovce": "Paňovce",
    "papin": "Papín",
    "papradno": "Papradno",
    "parchovany": "Parchovany",
    "parihuzovce": "Parihuzovce",
    "parnica": "Párnica",
    "partizanska lupca": "Partizánska Ľupča",
    "partizanske": "Partizánske",
    "paskova": "Pašková",
    "pastina zavada": "Paština Závada",
    "pastovce": "Pastovce",
    "pastuchov": "Pastuchov",
    "pata": "Pata",
    "patas": "Pataš",
    "patince": "Patince",
    "pavcina lehota": "Pavčina Lehota",
    "pavlany": "Pavľany",
    "pavlice": "Pavlice",
    "pavlova": "Pavlová",
    "pavlova ves": "Pavlova Ves",
    "pavlovce": "Pavlovce",
    "pavlovce nad uhom": "Pavlovce nad Uhom",
    "pazit": "Pažiť",
    "pcoline": "Pčoliné",
    "pecenady": "Pečeňady",
    "pecenany": "Pečeňany",
    "pecenice": "Pečenice",
    "pecovska nova ves": "Pečovská Nová Ves",
    "peder": "Peder",
    "perin-chym": "Perín-Chym",
    "pernek": "Pernek",
    "petkovce": "Petkovce",
    "petrikovce": "Petrikovce",
    "petrova": "Petrová",
    "petrova lehota": "Petrova Lehota",
    "petrova ves": "Petrova Ves",
    "petrovany": "Petrovany",
    "petrovce": "Petrovce",
    "petrovce nad laborcom": "Petrovce nad Laborcom",
    "petrovice": "Petrovice",
    "petrovo": "Petrovo",
    "pezinok": "Pezinok",
    "pichne": "Pichne",
    "piestany": "Piešťany",
    "pila": "Píla",
    "pincina": "Pinciná",
    "pinkovce": "Pinkovce",
    "piskorovce": "Piskorovce",
    "pitelova": "Pitelová",
    "plastovce": "Plášťovce",
    "plave vozokany": "Plavé Vozokany",
    "plavec": "Plaveč",
    "plavecke podhradie": "Plavecké Podhradie",
    "plavecky mikulas": "Plavecký Mikuláš",
    "plavecky peter": "Plavecký Peter",
    "plavecky stvrtok": "Plavecký Štvrtok",
    "plavnica": "Plavnica",
    "plechotice": "Plechotice",
    "ples": "Pleš",
    "plesivec": "Plešivec",
    "plevnik-drienove": "Plevník-Drienové",
    "pliesovce": "Pliešovce",
    "ploske": "Ploské",
    "pobedim": "Pobedim",
    "pocarova": "Počarová",
    "pochabany": "Pochabany",
    "pocuvadlo": "Počúvadlo",
    "podbiel": "Podbiel",
    "podbranc": "Podbranč",
    "podbrezova": "Podbrezová",
    "podhajska": "Podhájska",
    "podhorany": "Podhorany",
    "podhorie": "Podhorie",
    "podhorod": "Podhoroď",
    "podhradie": "Podhradie",
    "podhradik": "Podhradík",
    "podkonice": "Podkonice",
    "podkrivan": "Podkriváň",
    "podkylava": "Podkylava",
    "podluzany": "Podlužany",
    "podolie": "Podolie",
    "podolinec": "Podolínec",
    "podrecany": "Podrečany",
    "podskalie": "Podskalie",
    "podturen": "Podtureň",
    "podvysoka": "Podvysoká",
    "podzamcok": "Podzámčok",
    "pohorela": "Pohorelá",
    "pohranice": "Pohranice",
    "pohronska polhora": "Pohronská Polhora",
    "pohronsky bukovec": "Pohronský Bukovec",
    "pohronsky ruskov": "Pohronský Ruskov",
    "pokryvac": "Pokryváč",
    "polanovce": "Poľanovce",
    "polany": "Poľany",
    "poliakovce": "Poliakovce",
    "polianka": "Polianka",
    "polichno": "Polichno",
    "polina": "Polina",
    "polny kesov": "Poľný Kesov",
    "poloma": "Poloma",
    "polomka": "Polomka",
    "poltar": "Poltár",
    "poluvsie": "Poluvsie",
    "pongracovce": "Pongrácovce",
    "poniky": "Poniky",
    "poprad": "Poprad",
    "poproc": "Poproč",
    "popudinske mocidlany": "Popudinské Močidľany",
    "porac": "Poráč",
    "poriadie": "Poriadie",
    "porostov": "Porostov",
    "poruba": "Poruba",
    "poruba pod vihorlatom": "Poruba pod Vihorlatom",
    "porubka": "Porúbka",
    "posa": "Poša",
    "potocky": "Potôčky",
    "potok": "Potok",
    "potoky": "Potoky",
    "potonske luky": "Potônske Lúky",
    "potor": "Pôtor",
    "potvorice": "Potvorice",
    "povazany": "Považany",
    "povazska bystrica": "Považská Bystrica",
    "povina": "Povina",
    "povoda": "Povoda",
    "povraznik": "Povrazník",
    "pozba": "Pozba",
    "pozdisovce": "Pozdišovce",
    "praha": "Praha",
    "prakovce": "Prakovce",
    "prasice": "Prašice",
    "prasnik": "Prašník",
    "pravenec": "Pravenec",
    "pravica": "Pravica",
    "pravotice": "Pravotice",
    "praznovce": "Práznovce",
    "precin": "Prečín",
    "predajna": "Predajná",
    "predmier": "Predmier",
    "prencov": "Prenčov",
    "preselany": "Preseľany",
    "presov": "Prešov",
    "prestavlky": "Prestavlky",
    "pribelce": "Príbelce",
    "pribenik": "Pribeník",
    "pribeta": "Pribeta",
    "pribis": "Pribiš",
    "pribovce": "Príbovce",
    "pribylina": "Pribylina",
    "priechod": "Priechod",
    "priekopa": "Priekopa",
    "priepasne": "Priepasné",
    "prietrz": "Prietrž",
    "prietrzka": "Prietržka",
    "prievaly": "Prievaly",
    "prievidza": "Prievidza",
    "prihradzany": "Prihradzany",
    "prikra": "Príkra",
    "prislop": "Príslop",
    "pritulany": "Prituľany",
    "proc": "Proč",
    "prochot": "Prochot",
    "prosacov": "Prosačov",
    "prosiek": "Prosiek",
    "prsa": "Prša",
    "pruske": "Pruské",
    "prusy": "Prusy",
    "pruzina": "Pružina",
    "pstrina": "Pstriná",
    "pticie": "Ptičie",
    "ptruksa": "Ptrukša",
    "puchov": "Púchov",
    "pucov": "Pucov",
    "pukanec": "Pukanec",
    "pusovce": "Pušovce",
    "puste cemerne": "Pusté Čemerné",
    "puste pole": "Pusté Pole",
    "puste sady": "Pusté Sady",
    "puste ulany": "Pusté Úľany",
    "rabca": "Rabča",
    "rabcice": "Rabčice",
    "rad": "Rad",
    "radatice": "Radatice",
    "radava": "Radava",
    "radimov": "Radimov",
    "radnovce": "Radnovce",
    "radobica": "Radobica",
    "radola": "Radoľa",
    "radoma": "Radoma",
    "radosina": "Radošina",
    "radosovce": "Radošovce",
    "radostka": "Radôstka",
    "radvan nad dunajom": "Radvaň nad Dunajom",
    "radvan nad laborcom": "Radvaň nad Laborcom",
    "radvanovce": "Radvanovce",
    "radzovce": "Radzovce",
    "rafajovce": "Rafajovce",
    "rajcany": "Rajčany",
    "rajec": "Rajec",
    "rajecka lesna": "Rajecká Lesná",
    "rajecke teplice": "Rajecké Teplice",
    "rakos": "Rákoš",
    "rakova": "Raková",
    "rakovcik": "Rakovčík",
    "rakovec nad ondavou": "Rakovec nad Ondavou",
    "rakovice": "Rakovice",
    "rakovnica": "Rakovnica",
    "rakovo": "Rakovo",
    "raksa": "Rakša",
    "rakusy": "Rakúsy",
    "rakytnik": "Rakytník",
    "rankovce": "Rankovce",
    "rapovce": "Rapovce",
    "rasice": "Rašice",
    "raslavice": "Raslavice",
    "rastislavice": "Rastislavice",
    "ratka": "Ratka",
    "ratkova": "Ratková",
    "ratkovce": "Ratkovce",
    "ratkovo": "Ratkovo",
    "ratkovska lehota": "Ratkovská Lehota",
    "ratkovska sucha": "Ratkovská Suchá",
    "ratkovske bystre": "Ratkovské Bystré",
    "ratnovce": "Ratnovce",
    "ratvaj": "Ratvaj",
    "raznany": "Ražňany",
    "raztocno": "Ráztočno",
    "raztoka": "Ráztoka",
    "reca": "Reca",
    "regetovka": "Regetovka",
    "rejdova": "Rejdová",
    "relov": "Reľov",
    "remeniny": "Remeniny",
    "remetske hamre": "Remetské Hámre",
    "rencisov": "Renčišov",
    "repejov": "Repejov",
    "repiste": "Repište",
    "resica": "Rešica",
    "resov": "Rešov",
    "revuca": "Revúca",
    "revucka lehota": "Revúcka Lehota",
    "richnava": "Richnava",
    "richvald": "Richvald",
    "riecka": "Riečka",
    "rimavska bana": "Rimavská Baňa",
    "rimavska sec": "Rimavská Seč",
    "rimavska sobota": "Rimavská Sobota",
    "rimavske brezovo": "Rimavské Brezovo",
    "rimavske janovce": "Rimavské Janovce",
    "rimavske zaluzany": "Rimavské Zalužany",
    "risnovce": "Rišňovce",
    "rochovce": "Rochovce",
    "rohov": "Rohov",
    "rohovce": "Rohovce",
    "rohoznik": "Rohožník",
    "rokycany": "Rokycany",
    "rokytov": "Rokytov",
    "rokytov pri humennom": "Rokytov pri Humennom",
    "rokytovce": "Rokytovce",
    "rosina": "Rosina",
    "roskovce": "Roškovce",
    "rostar": "Roštár",
    "rovensko": "Rovensko",
    "rovinka": "Rovinka",
    "rovnany": "Rovňany",
    "rovne": "Rovné",
    "rozhanovce": "Rozhanovce",
    "rozkovany": "Rožkovany",
    "rozlozna": "Rozložná",
    "roznava": "Rožňava",
    "roznavske bystre": "Rožňavské Bystré",
    "roztoky": "Roztoky",
    "ruban": "Rúbaň",
    "rudina": "Rudina",
    "rudinka": "Rudinka",
    "rudinska": "Rudinská",
    "rudlov": "Rudlov",
    "rudna": "Rudná",
    "rudnany": "Rudňany",
    "rudnianska lehota": "Rudnianska Lehota",
    "rudnik": "Rudník",
    "rudno": "Rudno",
    "rudno nad hronom": "Rudno nad Hronom",
    "rumanova": "Rumanová",
    "rumince": "Rumince",
    "runina": "Runina",
    "ruska": "Ruská",
    "ruska bystra": "Ruská Bystrá",
    "ruska kajna": "Ruská Kajňa",
    "ruska nova ves": "Ruská Nová Ves",
    "ruska poruba": "Ruská Poruba",
    "ruska vola": "Ruská Voľa",
    "ruska vola nad popradom": "Ruská Voľa nad Popradom",
    "ruska volova": "Ruská Volová",
    "ruskov": "Ruskov",
    "ruskovce": "Ruskovce",
    "rusky hrabovec": "Ruský Hrabovec",
    "rusky potok": "Ruský Potok",
    "ruzina": "Ružiná",
    "ruzindol": "Ružindol",
    "ruzomberok": "Ružomberok",
    "rybany": "Rybany",
    "rybky": "Rybky",
    "rybnik": "Rybník",
    "rykyncice": "Rykynčice",
    "sabinov": "Sabinov",
    "sacurov": "Sačurov",
    "sadocne": "Sádočné",
    "sady nad torysou": "Sady nad Torysou",
    "sahy": "Šahy",
    "sajdikove humence": "Šajdíkove Humence",
    "sala": "Šaľa",
    "salgocka": "Šalgočka",
    "salgovce": "Šalgovce",
    "salka": "Salka",
    "salov": "Šalov",
    "sambron": "Šambron",
    "samorin": "Šamorín",
    "samudovce": "Šamudovce",
    "sandal": "Šandal",
    "santovka": "Santovka",
    "sap": "Sap",
    "sarbov": "Šarbov",
    "sarisska poruba": "Šarišská Poruba",
    "sarisska trstena": "Šarišská Trstená",
    "sarisske bohdanovce": "Šarišské Bohdanovce",
    "sarisske cierne": "Šarišské Čierne",
    "sarisske dravce": "Šarišské Dravce",
    "sarisske jastrabie": "Šarišské Jastrabie",
    "sarisske michalany": "Šarišské Michaľany",
    "sarisske sokolovce": "Šarišské Sokolovce",
    "sarissky stiavnik": "Šarišský Štiavnik",
    "sarkan": "Šarkan",
    "sarovce": "Šarovce",
    "sasa": "Sása",
    "sasinkovo": "Sasinkovo",
    "sasova": "Šašová",
    "sastin-straze": "Šaštín-Stráže",
    "savol": "Šávoľ",
    "sazdice": "Sazdice",
    "sebechleby": "Sebechleby",
    "sebedin-becov": "Sebedín-Bečov",
    "sebedrazie": "Sebedražie",
    "sec": "Seč",
    "secianky": "Sečianky",
    "secovce": "Sečovce",
    "secovska polianka": "Sečovská Polianka",
    "sedliacka dubova": "Sedliacka Dubová",
    "sedlice": "Sedlice",
    "sedliska": "Sedliská",
    "sedmerovec": "Sedmerovec",
    "sejkov": "Sejkov",
    "sekule": "Sekule",
    "selany": "Seľany",
    "selce": "Selce",
    "selec": "Selec",
    "selice": "Selice",
    "selpice": "Šelpice",
    "semerovo": "Semerovo",
    "semetkovce": "Šemetkovce",
    "semsa": "Šemša",
    "sena": "Seňa",
    "senec": "Senec",
    "seniakovce": "Seniakovce",
    "senica": "Senica",
    "senkvice": "Šenkvice",
    "senne": "Senné",
    "senohrad": "Senohrad",
    "sered": "Sereď",
    "siatorska bukovinka": "Šiatorská Bukovinka",
    "siba": "Šiba",
    "sid": "Šíd",
    "sielnica": "Sielnica",
    "sihelne": "Sihelné",
    "sihla": "Sihla",
    "sikenica": "Sikenica",
    "sikenicka": "Sikenička",
    "siladice": "Siladice",
    "silica": "Silica",
    "silicka brezova": "Silická Brezová",
    "silicka jablonica": "Silická Jablonica",
    "simonovce": "Šimonovce",
    "sindliar": "Šindliar",
    "sintava": "Šintava",
    "sipkov": "Šípkov",
    "sipkove": "Šípkové",
    "sirakov": "Širákov",
    "sirk": "Sirk",
    "sirkovce": "Širkovce",
    "sirnik": "Sirník",
    "siroke": "Široké",
    "sisov": "Šišov",
    "sivetice": "Šivetice",
    "skacany": "Skačany",
    "skalica": "Skalica",
    "skalite": "Skalité",
    "skalka nad vahom": "Skalka nad Váhom",
    "skaros": "Skároš",
    "skeresovo": "Skerešovo",
    "sklabina": "Sklabiňa",
    "sklabinsky podzamok": "Sklabinský Podzámok",
    "sklene": "Sklené",
    "sklene teplice": "Sklené Teplice",
    "skrabske": "Skrabské",
    "skycov": "Skýcov",
    "sladkovicovo": "Sládkovičovo",
    "slancik": "Slančík",
    "slanec": "Slanec",
    "slanska huta": "Slanská Huta",
    "slanske nove mesto": "Slanské Nové Mesto",
    "slaska": "Slaská",
    "slatina": "Slatina",
    "slatina nad bebravou": "Slatina nad Bebravou",
    "slatinka nad bebravou": "Slatinka nad Bebravou",
    "slatinske lazy": "Slatinské Lazy",
    "slatvina": "Slatvina",
    "slavec": "Slavec",
    "slavkovce": "Slavkovce",
    "slavnica": "Slavnica",
    "slavoska": "Slavoška",
    "slavosovce": "Slavošovce",
    "slazany": "Sľažany",
    "slepcany": "Slepčany",
    "sliac": "Sliač",
    "sliepkovce": "Sliepkovce",
    "slivnik": "Slivník",
    "slizke": "Slizké",
    "slopna": "Slopná",
    "slovany": "Slovany",
    "slovenska kajna": "Slovenská Kajňa",
    "slovenska lupca": "Slovenská Ľupča",
    "slovenska nova ves": "Slovenská Nová Ves",
    "slovenska ves": "Slovenská Ves",
    "slovenska volova": "Slovenská Volová",
    "slovenske darmoty": "Slovenské Ďarmoty",
    "slovenske klacany": "Slovenské Kľačany",
    "slovenske krive": "Slovenské Krivé",
    "slovenske nove mesto": "Slovenské Nové Mesto",
    "slovenske pravno": "Slovenské Pravno",
    "slovensky grob": "Slovenský Grob",
    "slovinky": "Slovinky",
    "smigovec": "Šmigovec",
    "smilno": "Smilno",
    "smizany": "Smižany",
    "smolenice": "Smolenice",
    "smolinske": "Smolinské",
    "smolnicka huta": "Smolnícka Huta",
    "smolnik": "Smolník",
    "smrdaky": "Smrdáky",
    "smrecany": "Smrečany",
    "snakov": "Snakov",
    "sneznica": "Snežnica",
    "snina": "Snina",
    "soblahov": "Soblahov",
    "sobos": "Soboš",
    "sobotiste": "Sobotište",
    "sobrance": "Sobrance",
    "socovce": "Socovce",
    "sokol": "Sokoľ",
    "sokolany": "Sokoľany",
    "sokolce": "Sokolce",
    "sokolovce": "Sokolovce",
    "sol": "Soľ",
    "solcany": "Solčany",
    "solcianky": "Solčianky",
    "solnicka": "Soľnička",
    "solnik": "Soľník",
    "solosnica": "Sološnica",
    "soltyska": "Šoltýska",
    "somotor": "Somotor",
    "sopkovce": "Sopkovce",
    "soporna": "Šoporňa",
    "spacince": "Špačince",
    "spania dolina": "Špania Dolina",
    "spanie pole": "Španie Pole",
    "spisska bela": "Spišská Belá",
    "spisska nova ves": "Spišská Nová Ves",
    "spisska stara ves": "Spišská Stará Ves",
    "spisska teplica": "Spišská Teplica",
    "spisske bystre": "Spišské Bystré",
    "spisske hanusovce": "Spišské Hanušovce",
    "spisske podhradie": "Spišské Podhradie",
    "spisske tomasovce": "Spišské Tomášovce",
    "spisske vlachy": "Spišské Vlachy",
    "spissky hrhov": "Spišský Hrhov",
    "spissky hrusov": "Spišský Hrušov",
    "spissky stiavnik": "Spišský Štiavnik",
    "spissky stvrtok": "Spišský Štvrtok",
    "srobarova": "Šrobárová",
    "stakcin": "Stakčín",
    "stakcinska roztoka": "Stakčínska Roztoka",
    "stanca": "Stanča",
    "stankovany": "Stankovany",
    "stankovce": "Stankovce",
    "stara basta": "Stará Bašta",
    "stara bystrica": "Stará Bystrica",
    "stara halic": "Stará Halič",
    "stara huta": "Stará Huta",
    "stara kremnicka": "Stará Kremnička",
    "stara lehota": "Stará Lehota",
    "stara lesna": "Stará Lesná",
    "stara lubovna": "Stará Ľubovňa",
    "stara myjava": "Stará Myjava",
    "stara tura": "Stará Turá",
    "stara voda": "Stará Voda",
    "stare": "Staré",
    "stare hory": "Staré Hory",
    "starina": "Starina",
    "stary hradok": "Starý Hrádok",
    "stary tekov": "Starý Tekov",
    "staskov": "Staškov",
    "staskovce": "Staškovce",
    "stebnicka huta": "Stebnícka Huta",
    "stebnik": "Stebník",
    "stefanov": "Štefanov",
    "stefanov nad oravou": "Štefanov nad Oravou",
    "stefanova": "Štefanová",
    "stefanovce": "Štefanovce",
    "stefanovicova": "Štefanovičová",
    "stefurov": "Štefurov",
    "sterusy": "Šterusy",
    "stiavnicka": "Štiavnička",
    "stiavnicke bane": "Štiavnické Bane",
    "stiavnik": "Štiavnik",
    "stitare": "Štitáre",
    "stitnik": "Štítnik",
    "stola": "Štôla",
    "stos": "Štós",
    "stozok": "Stožok",
    "stranany": "Stráňany",
    "stranavy": "Stráňavy",
    "strane pod tatrami": "Stráne pod Tatrami",
    "stranska": "Stránska",
    "stranske": "Stránske",
    "stratena": "Stratená",
    "straza": "Stráža",
    "strazne": "Strážne",
    "strazske": "Strážske",
    "strba": "Štrba",
    "strecno": "Strečno",
    "streda nad bodrogom": "Streda nad Bodrogom",
    "stredne plachtince": "Stredné Plachtince",
    "strekov": "Strekov",
    "strelniky": "Strelníky",
    "stretava": "Stretava",
    "stretavka": "Stretavka",
    "strezenice": "Streženice",
    "strihovce": "Strihovce",
    "strkovec": "Štrkovec",
    "strocin": "Stročín",
    "stropkov": "Stropkov",
    "studena": "Studená",
    "studenec": "Studenec",
    "studienka": "Studienka",
    "stulany": "Stuľany",
    "stupava": "Stupava",
    "stupne": "Stupné",
    "sturovo": "Štúrovo",
    "stvrtok": "Štvrtok",
    "stvrtok na ostrove": "Štvrtok na Ostrove",
    "sucany": "Sučany",
    "sucha dolina": "Suchá Dolina",
    "sucha hora": "Suchá Hora",
    "sucha nad parnou": "Suchá nad Parnou",
    "suchan": "Sucháň",
    "suche": "Suché",
    "suche brezovo": "Suché Brezovo",
    "suchohrad": "Suchohrad",
    "sudince": "Sudince",
    "sudovce": "Súdovce",
    "suja": "Šuja",
    "sukov": "Sukov",
    "sula": "Šuľa",
    "sulin": "Sulín",
    "sulov-hradna": "Súľov-Hradná",
    "sulovce": "Súlovce",
    "sumiac": "Šumiac",
    "sunava": "Šuňava",
    "surany": "Šurany",
    "surianky": "Šurianky",
    "surice": "Šurice",
    "surovce": "Šúrovce",
    "susany": "Sušany",
    "sutor": "Sútor",
    "sutovce": "Šútovce",
    "sutovo": "Šútovo",
    "svabovce": "Švábovce",
    "svata maria": "Svätá Mária",
    "svatoplukovo": "Svätoplukovo",
    "svatus": "Svätuš",
    "svatuse": "Svätuše",
    "svaty anton": "Svätý Anton",
    "svaty jur": "Svätý Jur",
    "svaty kriz": "Svätý Kríž",
    "svaty peter": "Svätý Peter",
    "svedernik": "Svederník",
    "svedlar": "Švedlár",
    "sverepec": "Sverepec",
    "sverzov": "Sveržov",
    "svetlice": "Svetlice",
    "svidnicka": "Svidnička",
    "svidnik": "Svidník",
    "svinia": "Svinia",
    "svinica": "Svinica",
    "svinice": "Svinice",
    "svinna": "Svinná",
    "svit": "Svit",
    "svodin": "Svodín",
    "svosov": "Švošov",
    "svrbice": "Svrbice",
    "svrcinovec": "Svrčinovec",
    "tachty": "Tachty",
    "tajna": "Tajná",
    "tajov": "Tajov",
    "tapesovo": "Ťapešovo",
    "tarnov": "Tarnov",
    "tasula": "Tašuľa",
    "tatranska javorina": "Tatranská Javorina",
    "tehla": "Tehla",
    "tekoldany": "Tekolďany",
    "tekovska breznica": "Tekovská Breznica",
    "tekovske luzany": "Tekovské Lužany",
    "tekovske nemce": "Tekovské Nemce",
    "tekovsky hradok": "Tekovský Hrádok",
    "telgart": "Telgárt",
    "telince": "Telince",
    "temes": "Temeš",
    "teplicka": "Teplička",
    "teplicka nad vahom": "Teplička nad Váhom",
    "teplicky": "Tepličky",
    "teply vrch": "Teplý Vrch",
    "terany": "Terany",
    "terchova": "Terchová",
    "teriakovce": "Teriakovce",
    "terna": "Terňa",
    "tesare": "Tesáre",
    "tesarske mlynany": "Tesárske Mlyňany",
    "tesedikovo": "Tešedíkovo",
    "tibava": "Tibava",
    "tichy potok": "Tichý Potok",
    "timoradza": "Timoradza",
    "tisinec": "Tisinec",
    "tisovec": "Tisovec",
    "tlmace": "Tlmače",
    "tocnica": "Točnica",
    "tokajik": "Tokajík",
    "tomasikovo": "Tomášikovo",
    "tomasov": "Tomášov",
    "tomasovce": "Tomášovce",
    "ton": "Tôň",
    "topola": "Topoľa",
    "topolcany": "Topoľčany",
    "topolcianky": "Topoľčianky",
    "topolnica": "Topoľnica",
    "topolniky": "Topoľníky",
    "topolovka": "Topoľovka",
    "toporec": "Toporec",
    "tornala": "Tornaľa",
    "torysa": "Torysa",
    "torysky": "Torysky",
    "tovarne": "Tovarné",
    "tovarnianska polianka": "Tovarnianska Polianka",
    "tovarniky": "Tovarníky",
    "trakovice": "Trakovice",
    "travnica": "Trávnica",
    "travnik": "Trávnik",
    "trebatice": "Trebatice",
    "trebejov": "Trebejov",
    "trebelovce": "Trebeľovce",
    "trebichava": "Trebichava",
    "trebisov": "Trebišov",
    "trebostovo": "Trebostovo",
    "trebusovce": "Trebušovce",
    "trenc": "Trenč",
    "trencianska tepla": "Trenčianska Teplá",
    "trencianska turna": "Trenčianska Turná",
    "trencianske bohuslavice": "Trenčianske Bohuslavice",
    "trencianske jastrabie": "Trenčianske Jastrabie",
    "trencianske mitice": "Trenčianske Mitice",
    "trencianske stankovce": "Trenčianske Stankovce",
    "trencianske teplice": "Trenčianske Teplice",
    "trencin": "Trenčín",
    "trhova hradska": "Trhová Hradská",
    "trhoviste": "Trhovište",
    "trnava": "Trnava",
    "trnava hora": "Trnavá Hora",
    "trnava pri laborci": "Trnava pri Laborci",
    "trnavka": "Trnávka",
    "trnie": "Tŕnie",
    "trnkov": "Trnkov",
    "trnovec": "Trnovec",
    "trnovec nad vahom": "Trnovec nad Váhom",
    "trnovo": "Trnovo",
    "trocany": "Tročany",
    "trpin": "Trpín",
    "trstany": "Trsťany",
    "trstena": "Trstená",
    "trstena na ostrove": "Trstená na Ostrove",
    "trstene": "Trstené",
    "trstene pri hornade": "Trstené pri Hornáde",
    "trstice": "Trstice",
    "trstin": "Trstín",
    "tuchyna": "Tuchyňa",
    "tuhar": "Tuhár",
    "tuhrina": "Tuhrina",
    "tulcik": "Tulčík",
    "tupa": "Tupá",
    "tura": "Turá",
    "turany": "Turany",
    "turany nad ondavou": "Turany nad Ondavou",
    "turcek": "Turček",
    "turcianky": "Turčianky",
    "turcianska stiavnicka": "Turčianska Štiavnička",
    "turcianske jaseno": "Turčianske Jaseno",
    "turcianske klacany": "Turčianske Kľačany",
    "turcianske teplice": "Turčianske Teplice",
    "turciansky dur": "Turčiansky Ďur",
    "turciansky peter": "Turčiansky Peter",
    "turcok": "Turčok",
    "turcovce": "Turcovce",
    "turecka": "Turecká",
    "turen": "Tureň",
    "turie": "Turie",
    "turik": "Turík",
    "turna nad bodvou": "Turňa nad Bodvou",
    "turnianska nova ves": "Turnianska Nová Ves",
    "turova": "Turová",
    "turzovka": "Turzovka",
    "tusice": "Tušice",
    "tusicka nova ves": "Tušická Nová Ves",
    "tuzina": "Tužina",
    "tvarozna": "Tvarožná",
    "tvrdomestice": "Tvrdomestice",
    "tvrdosin": "Tvrdošín",
    "tvrdosovce": "Tvrdošovce",
    "ubla": "Ubľa",
    "ubrez": "Úbrež",
    "udavske": "Udavské",
    "udica": "Udiča",
    "udol": "Údol",
    "uhliska": "Uhliská",
    "uhorna": "Úhorná",
    "uhorska ves": "Uhorská Ves",
    "uhorske": "Uhorské",
    "uhrovec": "Uhrovec",
    "uhrovske podhradie": "Uhrovské Podhradie",
    "ulany nad zitavou": "Úľany nad Žitavou",
    "ulic": "Ulič",
    "ulicske krive": "Uličské Krivé",
    "uloza": "Uloža",
    "unatin": "Uňatín",
    "unin": "Unín",
    "urmince": "Urmince",
    "utekac": "Utekáč",
    "uzovce": "Uzovce",
    "uzovska panica": "Uzovská Panica",
    "uzovske peklany": "Uzovské Pekľany",
    "uzovsky salgov": "Uzovský Šalgov",
    "vadovce": "Vaďovce",
    "vagrinec": "Vagrinec",
    "vahovce": "Váhovce",
    "vajkovce": "Vajkovce",
    "valaliky": "Valaliky",
    "valaska": "Valaská",
    "valaska bela": "Valaská Belá",
    "valaska dubova": "Valaská Dubová",
    "valaskovce (vojensky obvod)": "Valaškovce (vojenský obvod)",
    "valca": "Valča",
    "valentovce": "Valentovce",
    "valice": "Valice",
    "valkovce": "Valkovce",
    "valkovna": "Vaľkovňa",
    "vaniskovce": "Vaniškovce",
    "vapenik": "Vápeník",
    "varadka": "Varadka",
    "varechovce": "Varechovce",
    "varhanovce": "Varhaňovce",
    "varin": "Varín",
    "vasilov": "Vasiľov",
    "vavrecka": "Vavrečka",
    "vavrinec": "Vavrinec",
    "vavrisovo": "Vavrišovo",
    "vazec": "Važec",
    "vcelince": "Včelince",
    "vecelkov": "Večelkov",
    "vechec": "Vechec",
    "velaty": "Veľaty",
    "velcice": "Velčice",
    "velicna": "Veličná",
    "velka calomija": "Veľká Čalomija",
    "velka causa": "Veľká Čausa",
    "velka cierna": "Veľká Čierna",
    "velka dolina": "Veľká Dolina",
    "velka frankova": "Veľká Franková",
    "velka hradna": "Veľká Hradná",
    "velka ida": "Veľká Ida",
    "velka lehota": "Veľká Lehota",
    "velka lesna": "Veľká Lesná",
    "velka lodina": "Veľká Lodina",
    "velka lomnica": "Veľká Lomnica",
    "velka luka": "Veľká Lúka",
    "velka maca": "Veľká Mača",
    "velka nad iplom": "Veľká nad Ipľom",
    "velka paka": "Veľká Paka",
    "velka trna": "Veľká Tŕňa",
    "velka ves": "Veľká Ves",
    "velka ves nad iplom": "Veľká Ves nad Ipľom",
    "velke bierovce": "Veľké Bierovce",
    "velke blahovo": "Veľké Blahovo",
    "velke borove": "Veľké Borové",
    "velke chlievany": "Veľké Chlievany",
    "velke chyndice": "Veľké Chyndice",
    "velke dravce": "Veľké Dravce",
    "velke drzkovce": "Veľké Držkovce",
    "velke dvorany": "Veľké Dvorany",
    "velke dvorniky": "Veľké Dvorníky",
    "velke hoste": "Veľké Hoste",
    "velke kapusany": "Veľké Kapušany",
    "velke kosihy": "Veľké Kosihy",
    "velke kostolany": "Veľké Kostoľany",
    "velke kozmalovce": "Veľké Kozmálovce",
    "velke krstenany": "Veľké Kršteňany",
    "velke levare": "Veľké Leváre",
    "velke lovce": "Veľké Lovce",
    "velke ludince": "Veľké Ludince",
    "velke orviste": "Veľké Orvište",
    "velke ozorovce": "Veľké Ozorovce",
    "velke pole": "Veľké Pole",
    "velke raskovce": "Veľké Raškovce",
    "velke revistia": "Veľké Revištia",
    "velke ripnany": "Veľké Ripňany",
    "velke rovne": "Veľké Rovné",
    "velke slemence": "Veľké Slemence",
    "velke straciny": "Veľké Straciny",
    "velke teriakovce": "Veľké Teriakovce",
    "velke trakany": "Veľké Trakany",
    "velke turovce": "Veľké Turovce",
    "velke uherce": "Veľké Uherce",
    "velke ulany": "Veľké Úľany",
    "velke vozokany": "Veľké Vozokany",
    "velke zaluzie": "Veľké Zálužie",
    "velke zlievce": "Veľké Zlievce",
    "velkrop": "Veľkrop",
    "velky biel": "Veľký Biel",
    "velky blh": "Veľký Blh",
    "velky cepcin": "Veľký Čepčín",
    "velky cetin": "Veľký Cetín",
    "velky dur": "Veľký Ďur",
    "velky folkmar": "Veľký Folkmar",
    "velky grob": "Veľký Grob",
    "velky hores": "Veľký Horeš",
    "velky kamenec": "Veľký Kamenec",
    "velky kliz": "Veľký Klíž",
    "velky krtis": "Veľký Krtíš",
    "velky kyr": "Veľký Kýr",
    "velky lapas": "Veľký Lapáš",
    "velky lipnik": "Veľký Lipník",
    "velky lom": "Veľký Lom",
    "velky meder": "Veľký Meder",
    "velky saris": "Veľký Šariš",
    "velky slavkov": "Veľký Slavkov",
    "velky slivnik": "Veľký Slivník",
    "velopolie": "Veľopolie",
    "velusovce": "Velušovce",
    "vernar": "Vernár",
    "vesele": "Veselé",
    "veterna poruba": "Veterná Poruba",
    "vidina": "Vidiná",
    "vieska": "Vieska",
    "vieska nad blhom": "Vieska nad Blhom",
    "vieska nad zitavou": "Vieska nad Žitavou",
    "viglas": "Vígľaš",
    "viglasska huta-kalinka": "Vígľašská Huta-Kalinka",
    "vikartovce": "Vikartovce",
    "vinica": "Vinica",
    "vinicky": "Viničky",
    "vinicne": "Viničné",
    "vinne": "Vinné",
    "vinodol": "Vinodol",
    "vinohrady nad vahom": "Vinohrady nad Váhom",
    "vinosady": "Vinosady",
    "virt": "Virt",
    "vislanka": "Vislanka",
    "vislava": "Vislava",
    "visnov": "Višňov",
    "visnove": "Višňové",
    "visolaje": "Visolaje",
    "vistuk": "Vištuk",
    "vitanova": "Vitanová",
    "vitaz": "Víťaz",
    "vitazovce": "Víťazovce",
    "vitkovce": "Vítkovce",
    "vlaca": "Vlača",
    "vlachovo": "Vlachovo",
    "vlachy": "Vlachy",
    "vladica": "Vladiča",
    "vlcany": "Vlčany",
    "vlckovce": "Vlčkovce",
    "vlkanova": "Vlkanová",
    "vlkas": "Vlkas",
    "vlkova": "Vlková",
    "vlkovce": "Vlkovce",
    "vlky": "Vlky",
    "vlkyna": "Vlkyňa",
    "voderady": "Voderady",
    "vojany": "Vojany",
    "vojcice": "Vojčice",
    "vojka": "Vojka",
    "vojka nad dunajom": "Vojka nad Dunajom",
    "vojkovce": "Vojkovce",
    "vojnany": "Vojňany",
    "vojnatina": "Vojnatina",
    "vojtovce": "Vojtovce",
    "vola": "Voľa",
    "volica": "Volica",
    "volkovce": "Volkovce",
    "voznica": "Voznica",
    "vozokany": "Vozokany",
    "vrable": "Vráble",
    "vradiste": "Vrádište",
    "vrakun": "Vrakúň",
    "vranov nad toplou": "Vranov nad Topľou",
    "vrbnica": "Vrbnica",
    "vrbov": "Vrbov",
    "vrbova nad vahom": "Vrbová nad Váhom",
    "vrbovce": "Vrbovce",
    "vrbove": "Vrbové",
    "vrbovka": "Vrbovka",
    "vrchtepla": "Vrchteplá",
    "vricko": "Vrícko",
    "vrsatske podhradie": "Vršatské Podhradie",
    "vrutky": "Vrútky",
    "vtackovce": "Vtáčkovce",
    "vyborna": "Výborná",
    "vycapy-opatovce": "Výčapy-Opatovce",
    "vychodna": "Východná",
    "vydrany": "Vydrany",
    "vydrna": "Vydrná",
    "vydrnik": "Vydrník",
    "vyhne": "Vyhne",
    "vyrava": "Výrava",
    "vyskovce": "Vyškovce",
    "vyskovce nad iplom": "Vyškovce nad Ipľom",
    "vysna boca": "Vyšná Boca",
    "vysna hutka": "Vyšná Hutka",
    "vysna jablonka": "Vyšná Jablonka",
    "vysna jedlova": "Vyšná Jedľová",
    "vysna kamenica": "Vyšná Kamenica",
    "vysna mysla": "Vyšná Myšľa",
    "vysna olsava": "Vyšná Olšava",
    "vysna pisana": "Vyšná Pisaná",
    "vysna polianka": "Vyšná Polianka",
    "vysna rybnica": "Vyšná Rybnica",
    "vysna sebastova": "Vyšná Šebastová",
    "vysna sitnica": "Vyšná Sitnica",
    "vysna slana": "Vyšná Slaná",
    "vysna vola": "Vyšná Voľa",
    "vysne ladickovce": "Vyšné Ladičkovce",
    "vysne nad hronom": "Vyšné nad Hronom",
    "vysne nemecke": "Vyšné Nemecké",
    "vysne remety": "Vyšné Remety",
    "vysne repase": "Vyšné Repaše",
    "vysne ruzbachy": "Vyšné Ružbachy",
    "vysne valice": "Vyšné Valice",
    "vysny caj": "Vyšný Čaj",
    "vysny hrabovec": "Vyšný Hrabovec",
    "vysny hrusov": "Vyšný Hrušov",
    "vysny kazimir": "Vyšný Kazimír",
    "vysny klatov": "Vyšný Klátov",
    "vysny komarnik": "Vyšný Komárnik",
    "vysny krucov": "Vyšný Kručov",
    "vysny kubin": "Vyšný Kubín",
    "vysny medzev": "Vyšný Medzev",
    "vysny mirosov": "Vyšný Mirošov",
    "vysny orlik": "Vyšný Orlík",
    "vysny skalnik": "Vyšný Skálnik",
    "vysny slavkov": "Vyšný Slavkov",
    "vysny tvarozec": "Vyšný Tvarožec",
    "vysny zipov": "Vyšný Žipov",
    "vysocany": "Vysočany",
    "vysoka": "Vysoká",
    "vysoka nad kysucou": "Vysoká nad Kysucou",
    "vysoka nad uhom": "Vysoká nad Uhom",
    "vysoka pri morave": "Vysoká pri Morave",
    "vysoke tatry": "Vysoké Tatry",
    "zabiedovo": "Zábiedovo",
    "zabokreky": "Žabokreky",
    "zabokreky nad nitrou": "Žabokreky nad Nitrou",
    "zaborie": "Záborie",
    "zaborske": "Záborské",
    "zacharovce": "Zacharovce",
    "zadiel": "Zádiel",
    "zador": "Zádor",
    "zahor": "Záhor",
    "zahorce": "Záhorce",
    "zahorie (vojensky obvod)": "Záhorie (vojenský obvod)",
    "zahorska ves": "Záhorská Ves",
    "zahradne": "Záhradné",
    "zakamenne": "Zákamenné",
    "zakarovce": "Žakarovce",
    "zakopcie": "Zákopčie",
    "zakovce": "Žakovce",
    "zalaba": "Zalaba",
    "zalesie": "Zálesie",
    "zalobin": "Žalobín",
    "zaluzice": "Zalužice",
    "zamarovce": "Zamarovce",
    "zamutov": "Zámutov",
    "zariecie": "Záriečie",
    "zarnov": "Žarnov",
    "zarnovica": "Žarnovica",
    "zaskalie": "Záskalie",
    "zaskov": "Žaškov",
    "zatin": "Zatín",
    "zavada": "Závada",
    "zavadka": "Závadka",
    "zavadka nad hronom": "Závadka nad Hronom",
    "zavar": "Zavar",
    "zavazna poruba": "Závažná Poruba",
    "zavod": "Závod",
    "zazriva": "Zázrivá",
    "zbehnov": "Zbehňov",
    "zbehy": "Zbehy",
    "zbince": "Žbince",
    "zboj": "Zboj",
    "zbojne": "Zbojné",
    "zborov": "Zborov",
    "zborov nad bystricou": "Zborov nad Bystricou",
    "zbrojniky": "Zbrojníky",
    "zbudska bela": "Zbudská Belá",
    "zbudske dlhe": "Zbudské Dlhé",
    "zbudza": "Zbudza",
    "zbynov": "Zbyňov",
    "zdana": "Ždaňa",
    "zdiar": "Ždiar",
    "zehna": "Žehňa",
    "zehra": "Žehra",
    "zelenec": "Zeleneč",
    "zelezna breznica": "Železná Breznica",
    "zeleznik": "Železník",
    "zeliezovce": "Želiezovce",
    "zelmanovce": "Želmanovce",
    "zelovce": "Želovce",
    "zemberovce": "Žemberovce",
    "zemianska olca": "Zemianska Olča",
    "zemianske kostolany": "Zemianske Kostoľany",
    "zemianske podhradie": "Zemianske Podhradie",
    "zemianske sady": "Zemianske Sady",
    "zemiansky vrbovok": "Zemiansky Vrbovok",
    "zemliare": "Žemliare",
    "zemne": "Zemné",
    "zemplin": "Zemplín",
    "zemplinska nova ves": "Zemplínska Nová Ves",
    "zemplinska siroka": "Zemplínska Široká",
    "zemplinska teplica": "Zemplínska Teplica",
    "zemplinske hamre": "Zemplínske Hámre",
    "zemplinske hradiste": "Zemplínske Hradište",
    "zemplinske jastrabie": "Zemplínske Jastrabie",
    "zemplinske kopcany": "Zemplínske Kopčany",
    "zemplinsky branc": "Zemplínsky Branč",
    "ziar": "Žiar",
    "ziar nad hronom": "Žiar nad Hronom",
    "zibritov": "Žibritov",
    "ziharec": "Žihárec",
    "zikava": "Žikava",
    "zilina": "Žilina",
    "zip": "Žíp",
    "zipov": "Žipov",
    "zirany": "Žirany",
    "zitavany": "Žitavany",
    "zitavce": "Žitavce",
    "zitna-radisa": "Žitná-Radiša",
    "zlata bana": "Zlatá Baňa",
    "zlata idka": "Zlatá Idka",
    "zlate": "Zlaté",
    "zlate klasy": "Zlaté Klasy",
    "zlate moravce": "Zlaté Moravce",
    "zlatna na ostrove": "Zlatná na Ostrove",
    "zlatnik": "Zlatník",
    "zlatniky": "Zlatníky",
    "zlatno": "Zlatno",
    "zliechov": "Zliechov",
    "zlkovce": "Žlkovce",
    "zohor": "Zohor",
    "zombor": "Zombor",
    "zubak": "Zubák",
    "zuberec": "Zuberec",
    "zubne": "Zubné",
    "zubrohlava": "Zubrohlava",
    "zupcany": "Župčany",
    "zupkov": "Župkov",
    "zvolen": "Zvolen",
    "zvolenska slatina": "Zvolenská Slatina",
    "zvoncin": "Zvončín",
}
